// @generated by buffa-codegen. DO NOT EDIT.

include!("sf.substreams.ethereum.v1.call.rs");
include!("sf.substreams.ethereum.v1.event.rs");
include!("sf.substreams.ethereum.v1.events_and_calls.rs");
include!("sf.substreams.ethereum.v1.transaction.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.substreams.ethereum.v1.call.__view.rs");
        include!("sf.substreams.ethereum.v1.event.__view.rs");
        include!("sf.substreams.ethereum.v1.events_and_calls.__view.rs");
        include!("sf.substreams.ethereum.v1.transaction.__view.rs");
    }
    pub mod lazy_view {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.substreams.ethereum.v1.call.__lazy_view.rs");
        include!("sf.substreams.ethereum.v1.event.__lazy_view.rs");
        include!("sf.substreams.ethereum.v1.events_and_calls.__lazy_view.rs");
        include!("sf.substreams.ethereum.v1.transaction.__lazy_view.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::CallsView;
#[doc(inline)]
pub use self::__buffa::view::CallsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::CallsLazyView;
#[doc(inline)]
pub use self::__buffa::view::CallView;
#[doc(inline)]
pub use self::__buffa::view::CallOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::CallLazyView;
#[doc(inline)]
pub use self::__buffa::view::EventsView;
#[doc(inline)]
pub use self::__buffa::view::EventsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::EventsLazyView;
#[doc(inline)]
pub use self::__buffa::view::EventView;
#[doc(inline)]
pub use self::__buffa::view::EventOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::EventLazyView;
#[doc(inline)]
pub use self::__buffa::view::EventsAndCallsView;
#[doc(inline)]
pub use self::__buffa::view::EventsAndCallsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::EventsAndCallsLazyView;
#[doc(inline)]
pub use self::__buffa::view::TransactionsView;
#[doc(inline)]
pub use self::__buffa::view::TransactionsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::TransactionsLazyView;
#[doc(inline)]
pub use self::__buffa::view::TransactionView;
#[doc(inline)]
pub use self::__buffa::view::TransactionOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::TransactionLazyView;
