// @generated by buffa-codegen. DO NOT EDIT.

include!("sf.cosmos.type.v2.block.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.cosmos.type.v2.block.__view.rs");
        pub mod oneof {
            #[allow(unused_imports)]
            use super::*;
            include!("sf.cosmos.type.v2.block.__view_oneof.rs");
        }
    }
    pub mod lazy_view {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.cosmos.type.v2.block.__lazy_view.rs");
    }
    pub mod oneof {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.cosmos.type.v2.block.__oneof.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::BlockView;
#[doc(inline)]
pub use self::__buffa::view::BlockOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::BlockLazyView;
#[doc(inline)]
pub use self::__buffa::view::HeaderView;
#[doc(inline)]
pub use self::__buffa::view::HeaderOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::HeaderLazyView;
#[doc(inline)]
pub use self::__buffa::view::ConsensusView;
#[doc(inline)]
pub use self::__buffa::view::ConsensusOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::ConsensusLazyView;
#[doc(inline)]
pub use self::__buffa::view::BlockIDView;
#[doc(inline)]
pub use self::__buffa::view::BlockIDOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::BlockIDLazyView;
#[doc(inline)]
pub use self::__buffa::view::PartSetHeaderView;
#[doc(inline)]
pub use self::__buffa::view::PartSetHeaderOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::PartSetHeaderLazyView;
#[doc(inline)]
pub use self::__buffa::view::MisbehaviorView;
#[doc(inline)]
pub use self::__buffa::view::MisbehaviorOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::MisbehaviorLazyView;
#[doc(inline)]
pub use self::__buffa::view::ValidatorView;
#[doc(inline)]
pub use self::__buffa::view::ValidatorOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::ValidatorLazyView;
#[doc(inline)]
pub use self::__buffa::view::EventView;
#[doc(inline)]
pub use self::__buffa::view::EventOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::EventLazyView;
#[doc(inline)]
pub use self::__buffa::view::EventAttributeView;
#[doc(inline)]
pub use self::__buffa::view::EventAttributeOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::EventAttributeLazyView;
#[doc(inline)]
pub use self::__buffa::view::EventBytesView;
#[doc(inline)]
pub use self::__buffa::view::EventBytesOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::EventBytesLazyView;
#[doc(inline)]
pub use self::__buffa::view::EventAttributeBytesView;
#[doc(inline)]
pub use self::__buffa::view::EventAttributeBytesOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::EventAttributeBytesLazyView;
#[doc(inline)]
pub use self::__buffa::view::TxResultsView;
#[doc(inline)]
pub use self::__buffa::view::TxResultsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::TxResultsLazyView;
#[doc(inline)]
pub use self::__buffa::view::ValidatorUpdateView;
#[doc(inline)]
pub use self::__buffa::view::ValidatorUpdateOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::ValidatorUpdateLazyView;
#[doc(inline)]
pub use self::__buffa::view::PublicKeyView;
#[doc(inline)]
pub use self::__buffa::view::PublicKeyOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::PublicKeyLazyView;
#[doc(inline)]
pub use self::__buffa::view::ConsensusParamsView;
#[doc(inline)]
pub use self::__buffa::view::ConsensusParamsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::ConsensusParamsLazyView;
#[doc(inline)]
pub use self::__buffa::view::BlockParamsView;
#[doc(inline)]
pub use self::__buffa::view::BlockParamsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::BlockParamsLazyView;
#[doc(inline)]
pub use self::__buffa::view::EvidenceParamsView;
#[doc(inline)]
pub use self::__buffa::view::EvidenceParamsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::EvidenceParamsLazyView;
#[doc(inline)]
pub use self::__buffa::view::ValidatorParamsView;
#[doc(inline)]
pub use self::__buffa::view::ValidatorParamsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::ValidatorParamsLazyView;
#[doc(inline)]
pub use self::__buffa::view::VersionParamsView;
#[doc(inline)]
pub use self::__buffa::view::VersionParamsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::VersionParamsLazyView;
#[doc(inline)]
pub use self::__buffa::view::HashedParamsView;
#[doc(inline)]
pub use self::__buffa::view::HashedParamsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::HashedParamsLazyView;
