// @generated by buffa-codegen. DO NOT EDIT.
// source: sf/substreams/sink/service/v1/service.proto

#[allow(non_camel_case_types)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(i32)]
pub enum DeploymentStatus {
    UNKNOWN = 0i32,
    RUNNING = 1i32,
    FAILING = 2i32,
    PAUSED = 3i32,
    STOPPED = 4i32,
    STARTING = 5i32,
    PAUSING = 6i32,
    STOPPING = 7i32,
    REMOVING = 8i32,
    RESUMING = 9i32,
}
impl DeploymentStatus {
    ///Idiomatic alias for [`Self::UNKNOWN`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Unknown: Self = Self::UNKNOWN;
    ///Idiomatic alias for [`Self::RUNNING`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Running: Self = Self::RUNNING;
    ///Idiomatic alias for [`Self::FAILING`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Failing: Self = Self::FAILING;
    ///Idiomatic alias for [`Self::PAUSED`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Paused: Self = Self::PAUSED;
    ///Idiomatic alias for [`Self::STOPPED`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Stopped: Self = Self::STOPPED;
    ///Idiomatic alias for [`Self::STARTING`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Starting: Self = Self::STARTING;
    ///Idiomatic alias for [`Self::PAUSING`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Pausing: Self = Self::PAUSING;
    ///Idiomatic alias for [`Self::STOPPING`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Stopping: Self = Self::STOPPING;
    ///Idiomatic alias for [`Self::REMOVING`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Removing: Self = Self::REMOVING;
    ///Idiomatic alias for [`Self::RESUMING`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Resuming: Self = Self::RESUMING;
}
impl ::core::default::Default for DeploymentStatus {
    fn default() -> Self {
        Self::UNKNOWN
    }
}
impl ::buffa::Enumeration for DeploymentStatus {
    fn from_i32(value: i32) -> ::core::option::Option<Self> {
        match value {
            0i32 => ::core::option::Option::Some(Self::UNKNOWN),
            1i32 => ::core::option::Option::Some(Self::RUNNING),
            2i32 => ::core::option::Option::Some(Self::FAILING),
            3i32 => ::core::option::Option::Some(Self::PAUSED),
            4i32 => ::core::option::Option::Some(Self::STOPPED),
            5i32 => ::core::option::Option::Some(Self::STARTING),
            6i32 => ::core::option::Option::Some(Self::PAUSING),
            7i32 => ::core::option::Option::Some(Self::STOPPING),
            8i32 => ::core::option::Option::Some(Self::REMOVING),
            9i32 => ::core::option::Option::Some(Self::RESUMING),
            _ => ::core::option::Option::None,
        }
    }
    fn to_i32(&self) -> i32 {
        *self as i32
    }
    fn proto_name(&self) -> &'static str {
        match self {
            Self::UNKNOWN => "UNKNOWN",
            Self::RUNNING => "RUNNING",
            Self::FAILING => "FAILING",
            Self::PAUSED => "PAUSED",
            Self::STOPPED => "STOPPED",
            Self::STARTING => "STARTING",
            Self::PAUSING => "PAUSING",
            Self::STOPPING => "STOPPING",
            Self::REMOVING => "REMOVING",
            Self::RESUMING => "RESUMING",
        }
    }
    fn from_proto_name(name: &str) -> ::core::option::Option<Self> {
        match name {
            "UNKNOWN" => ::core::option::Option::Some(Self::UNKNOWN),
            "RUNNING" => ::core::option::Option::Some(Self::RUNNING),
            "FAILING" => ::core::option::Option::Some(Self::FAILING),
            "PAUSED" => ::core::option::Option::Some(Self::PAUSED),
            "STOPPED" => ::core::option::Option::Some(Self::STOPPED),
            "STARTING" => ::core::option::Option::Some(Self::STARTING),
            "PAUSING" => ::core::option::Option::Some(Self::PAUSING),
            "STOPPING" => ::core::option::Option::Some(Self::STOPPING),
            "REMOVING" => ::core::option::Option::Some(Self::REMOVING),
            "RESUMING" => ::core::option::Option::Some(Self::RESUMING),
            _ => ::core::option::Option::None,
        }
    }
    fn values() -> &'static [Self] {
        &[
            Self::UNKNOWN,
            Self::RUNNING,
            Self::FAILING,
            Self::PAUSED,
            Self::STOPPED,
            Self::STARTING,
            Self::PAUSING,
            Self::STOPPING,
            Self::REMOVING,
            Self::RESUMING,
        ]
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct DeployRequest {
    /// Field 1: `substreams_package`
    pub substreams_package: ::buffa::MessageField<
        super::super::super::v1::Package,
        ::buffa::Inline<super::super::super::v1::Package>,
    >,
    /// Field 2: `development_mode`
    pub development_mode: bool,
    /// Field 3: `parameters`
    pub parameters: ::buffa::alloc::vec::Vec<Parameter>,
}
impl ::core::fmt::Debug for DeployRequest {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("DeployRequest")
            .field("substreams_package", &self.substreams_package)
            .field("development_mode", &self.development_mode)
            .field("parameters", &self.parameters)
            .finish()
    }
}
impl DeployRequest {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.DeployRequest";
}
::buffa::impl_default_instance!(DeployRequest);
impl ::buffa::MessageName for DeployRequest {
    const PACKAGE: &'static str = "sf.substreams.sink.service.v1";
    const NAME: &'static str = "DeployRequest";
    const FULL_NAME: &'static str = "sf.substreams.sink.service.v1.DeployRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.DeployRequest";
}
impl ::buffa::Message for DeployRequest {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.substreams_package.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.substreams_package.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if self.development_mode {
            size += 1u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        for v in &self.parameters {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.substreams_package.is_set() {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.substreams_package.write_to(__cache, buf);
        }
        if self.development_mode {
            ::buffa::types::put_bool_field(2u32, self.development_mode, buf);
        }
        for v in &self.parameters {
            ::buffa::types::put_len_delimited_header(
                3u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.substreams_package.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.development_mode = ::buffa::types::decode_bool(buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&elem),
                )?;
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.parameters.push(elem);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.substreams_package = ::buffa::MessageField::none();
        self.development_mode = false;
        self.parameters.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct Parameter {
    /// Field 1: `key`
    pub key: ::buffa::alloc::string::String,
    /// Field 2: `value`
    pub value: ::buffa::alloc::string::String,
}
impl ::core::fmt::Debug for Parameter {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Parameter")
            .field("key", &self.key)
            .field("value", &self.value)
            .finish()
    }
}
impl Parameter {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.Parameter";
}
::buffa::impl_default_instance!(Parameter);
impl ::buffa::MessageName for Parameter {
    const PACKAGE: &'static str = "sf.substreams.sink.service.v1";
    const NAME: &'static str = "Parameter";
    const FULL_NAME: &'static str = "sf.substreams.sink.service.v1.Parameter";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.Parameter";
}
impl ::buffa::Message for Parameter {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.key.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.key) as u64;
        }
        if !self.value.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.value) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.key.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.key, buf);
        }
        if !self.value.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.value, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.key, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.value, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.key.clear();
        self.value.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct DeployResponse {
    /// Field 1: `status`
    pub status: ::buffa::EnumValue<DeploymentStatus>,
    /// deployment_id is a short name (max 8 characters) that uniquely identifies your deployment
    ///
    /// Field 2: `deployment_id`
    pub deployment_id: ::buffa::alloc::string::String,
    /// Field 3: `services`
    pub services: ::buffa::__private::HashMap<
        ::buffa::alloc::string::String,
        ::buffa::alloc::string::String,
    >,
    /// Field 4: `reason`
    pub reason: ::buffa::alloc::string::String,
    /// Field 5: `motd`
    pub motd: ::buffa::alloc::string::String,
}
impl ::core::fmt::Debug for DeployResponse {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("DeployResponse")
            .field("status", &self.status)
            .field("deployment_id", &self.deployment_id)
            .field("services", &self.services)
            .field("reason", &self.reason)
            .field("motd", &self.motd)
            .finish()
    }
}
impl DeployResponse {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.DeployResponse";
}
::buffa::impl_default_instance!(DeployResponse);
impl ::buffa::MessageName for DeployResponse {
    const PACKAGE: &'static str = "sf.substreams.sink.service.v1";
    const NAME: &'static str = "DeployResponse";
    const FULL_NAME: &'static str = "sf.substreams.sink.service.v1.DeployResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.DeployResponse";
}
impl ::buffa::Message for DeployResponse {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        {
            let val = self.status.to_i32();
            if val != 0 {
                size += 1u64 + ::buffa::types::int32_encoded_len(val) as u64;
            }
        }
        if !self.deployment_id.is_empty() {
            size
                += 1u64 + ::buffa::types::string_encoded_len(&self.deployment_id) as u64;
        }
        size
            += ::buffa::map_codec::field_len::<
                ::buffa::map_codec::Str,
                ::buffa::map_codec::Str,
                _,
            >(&self.services, 1u64);
        if !self.reason.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.reason) as u64;
        }
        if !self.motd.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.motd) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        {
            let val = self.status.to_i32();
            if val != 0 {
                ::buffa::types::put_int32_field(1u32, val, buf);
            }
        }
        if !self.deployment_id.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.deployment_id, buf);
        }
        ::buffa::map_codec::write_field::<
            ::buffa::map_codec::Str,
            ::buffa::map_codec::Str,
            _,
        >(&self.services, 3u32, buf);
        if !self.reason.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.reason, buf);
        }
        if !self.motd.is_empty() {
            ::buffa::types::put_string_field(5u32, &self.motd, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.status = ::buffa::EnumValue::from(
                    ::buffa::types::decode_int32(buf)?,
                );
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.deployment_id, buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::map_codec::merge_entry::<
                    ::buffa::map_codec::Str,
                    ::buffa::map_codec::Str,
                    _,
                >(&mut self.services, buf, ctx)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.reason, buf)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.motd, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.status = ::buffa::EnumValue::from(0);
        self.deployment_id.clear();
        self.services.clear();
        self.reason.clear();
        self.motd.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct UpdateRequest {
    /// Field 1: `substreams_package`
    pub substreams_package: ::buffa::MessageField<
        super::super::super::v1::Package,
        ::buffa::Inline<super::super::super::v1::Package>,
    >,
    /// Field 2: `deployment_id`
    pub deployment_id: ::buffa::alloc::string::String,
    /// Field 3: `reset`
    pub reset: bool,
}
impl ::core::fmt::Debug for UpdateRequest {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("UpdateRequest")
            .field("substreams_package", &self.substreams_package)
            .field("deployment_id", &self.deployment_id)
            .field("reset", &self.reset)
            .finish()
    }
}
impl UpdateRequest {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.UpdateRequest";
}
::buffa::impl_default_instance!(UpdateRequest);
impl ::buffa::MessageName for UpdateRequest {
    const PACKAGE: &'static str = "sf.substreams.sink.service.v1";
    const NAME: &'static str = "UpdateRequest";
    const FULL_NAME: &'static str = "sf.substreams.sink.service.v1.UpdateRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.UpdateRequest";
}
impl ::buffa::Message for UpdateRequest {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.substreams_package.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.substreams_package.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if !self.deployment_id.is_empty() {
            size
                += 1u64 + ::buffa::types::string_encoded_len(&self.deployment_id) as u64;
        }
        if self.reset {
            size += 1u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.substreams_package.is_set() {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.substreams_package.write_to(__cache, buf);
        }
        if !self.deployment_id.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.deployment_id, buf);
        }
        if self.reset {
            ::buffa::types::put_bool_field(3u32, self.reset, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.substreams_package.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.deployment_id, buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.reset = ::buffa::types::decode_bool(buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.substreams_package = ::buffa::MessageField::none();
        self.deployment_id.clear();
        self.reset = false;
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct UpdateResponse {
    /// Field 1: `status`
    pub status: ::buffa::EnumValue<DeploymentStatus>,
    /// Field 2: `services`
    pub services: ::buffa::__private::HashMap<
        ::buffa::alloc::string::String,
        ::buffa::alloc::string::String,
    >,
    /// Field 3: `reason`
    pub reason: ::buffa::alloc::string::String,
    /// Field 4: `motd`
    pub motd: ::buffa::alloc::string::String,
}
impl ::core::fmt::Debug for UpdateResponse {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("UpdateResponse")
            .field("status", &self.status)
            .field("services", &self.services)
            .field("reason", &self.reason)
            .field("motd", &self.motd)
            .finish()
    }
}
impl UpdateResponse {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.UpdateResponse";
}
::buffa::impl_default_instance!(UpdateResponse);
impl ::buffa::MessageName for UpdateResponse {
    const PACKAGE: &'static str = "sf.substreams.sink.service.v1";
    const NAME: &'static str = "UpdateResponse";
    const FULL_NAME: &'static str = "sf.substreams.sink.service.v1.UpdateResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.UpdateResponse";
}
impl ::buffa::Message for UpdateResponse {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        {
            let val = self.status.to_i32();
            if val != 0 {
                size += 1u64 + ::buffa::types::int32_encoded_len(val) as u64;
            }
        }
        size
            += ::buffa::map_codec::field_len::<
                ::buffa::map_codec::Str,
                ::buffa::map_codec::Str,
                _,
            >(&self.services, 1u64);
        if !self.reason.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.reason) as u64;
        }
        if !self.motd.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.motd) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        {
            let val = self.status.to_i32();
            if val != 0 {
                ::buffa::types::put_int32_field(1u32, val, buf);
            }
        }
        ::buffa::map_codec::write_field::<
            ::buffa::map_codec::Str,
            ::buffa::map_codec::Str,
            _,
        >(&self.services, 2u32, buf);
        if !self.reason.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.reason, buf);
        }
        if !self.motd.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.motd, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.status = ::buffa::EnumValue::from(
                    ::buffa::types::decode_int32(buf)?,
                );
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::map_codec::merge_entry::<
                    ::buffa::map_codec::Str,
                    ::buffa::map_codec::Str,
                    _,
                >(&mut self.services, buf, ctx)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.reason, buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.motd, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.status = ::buffa::EnumValue::from(0);
        self.services.clear();
        self.reason.clear();
        self.motd.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct InfoRequest {
    /// Field 1: `deployment_id`
    pub deployment_id: ::buffa::alloc::string::String,
}
impl ::core::fmt::Debug for InfoRequest {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("InfoRequest")
            .field("deployment_id", &self.deployment_id)
            .finish()
    }
}
impl InfoRequest {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.InfoRequest";
}
::buffa::impl_default_instance!(InfoRequest);
impl ::buffa::MessageName for InfoRequest {
    const PACKAGE: &'static str = "sf.substreams.sink.service.v1";
    const NAME: &'static str = "InfoRequest";
    const FULL_NAME: &'static str = "sf.substreams.sink.service.v1.InfoRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.InfoRequest";
}
impl ::buffa::Message for InfoRequest {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.deployment_id.is_empty() {
            size
                += 1u64 + ::buffa::types::string_encoded_len(&self.deployment_id) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.deployment_id.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.deployment_id, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.deployment_id, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.deployment_id.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct InfoResponse {
    /// Field 1: `status`
    pub status: ::buffa::EnumValue<DeploymentStatus>,
    /// Field 2: `services`
    pub services: ::buffa::__private::HashMap<
        ::buffa::alloc::string::String,
        ::buffa::alloc::string::String,
    >,
    /// Field 3: `reason`
    pub reason: ::buffa::alloc::string::String,
    /// Field 4: `package_info`
    pub package_info: ::buffa::MessageField<PackageInfo, ::buffa::Inline<PackageInfo>>,
    /// Field 5: `progress`
    pub progress: ::buffa::MessageField<SinkProgress, ::buffa::Inline<SinkProgress>>,
    /// Field 6: `motd`
    pub motd: ::buffa::alloc::string::String,
}
impl ::core::fmt::Debug for InfoResponse {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("InfoResponse")
            .field("status", &self.status)
            .field("services", &self.services)
            .field("reason", &self.reason)
            .field("package_info", &self.package_info)
            .field("progress", &self.progress)
            .field("motd", &self.motd)
            .finish()
    }
}
impl InfoResponse {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.InfoResponse";
}
::buffa::impl_default_instance!(InfoResponse);
impl ::buffa::MessageName for InfoResponse {
    const PACKAGE: &'static str = "sf.substreams.sink.service.v1";
    const NAME: &'static str = "InfoResponse";
    const FULL_NAME: &'static str = "sf.substreams.sink.service.v1.InfoResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.InfoResponse";
}
impl ::buffa::Message for InfoResponse {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        {
            let val = self.status.to_i32();
            if val != 0 {
                size += 1u64 + ::buffa::types::int32_encoded_len(val) as u64;
            }
        }
        size
            += ::buffa::map_codec::field_len::<
                ::buffa::map_codec::Str,
                ::buffa::map_codec::Str,
                _,
            >(&self.services, 1u64);
        if !self.reason.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.reason) as u64;
        }
        if self.package_info.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.package_info.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if self.progress.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.progress.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if !self.motd.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.motd) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        {
            let val = self.status.to_i32();
            if val != 0 {
                ::buffa::types::put_int32_field(1u32, val, buf);
            }
        }
        ::buffa::map_codec::write_field::<
            ::buffa::map_codec::Str,
            ::buffa::map_codec::Str,
            _,
        >(&self.services, 2u32, buf);
        if !self.reason.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.reason, buf);
        }
        if self.package_info.is_set() {
            ::buffa::types::put_len_delimited_header(
                4u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.package_info.write_to(__cache, buf);
        }
        if self.progress.is_set() {
            ::buffa::types::put_len_delimited_header(
                5u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.progress.write_to(__cache, buf);
        }
        if !self.motd.is_empty() {
            ::buffa::types::put_string_field(6u32, &self.motd, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.status = ::buffa::EnumValue::from(
                    ::buffa::types::decode_int32(buf)?,
                );
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::map_codec::merge_entry::<
                    ::buffa::map_codec::Str,
                    ::buffa::map_codec::Str,
                    _,
                >(&mut self.services, buf, ctx)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.reason, buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.package_info.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.progress.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.motd, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.status = ::buffa::EnumValue::from(0);
        self.services.clear();
        self.reason.clear();
        self.package_info = ::buffa::MessageField::none();
        self.progress = ::buffa::MessageField::none();
        self.motd.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct SinkProgress {
    /// Field 1: `last_processed_block`
    pub last_processed_block: u64,
}
impl ::core::fmt::Debug for SinkProgress {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("SinkProgress")
            .field("last_processed_block", &self.last_processed_block)
            .finish()
    }
}
impl SinkProgress {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.SinkProgress";
}
::buffa::impl_default_instance!(SinkProgress);
impl ::buffa::MessageName for SinkProgress {
    const PACKAGE: &'static str = "sf.substreams.sink.service.v1";
    const NAME: &'static str = "SinkProgress";
    const FULL_NAME: &'static str = "sf.substreams.sink.service.v1.SinkProgress";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.SinkProgress";
}
impl ::buffa::Message for SinkProgress {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.last_processed_block != 0u64 {
            size
                += 1u64
                    + ::buffa::types::uint64_encoded_len(self.last_processed_block)
                        as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.last_processed_block != 0u64 {
            ::buffa::types::put_uint64_field(1u32, self.last_processed_block, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.last_processed_block = ::buffa::types::decode_uint64(buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.last_processed_block = 0u64;
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct PackageInfo {
    /// Field 1: `name`
    pub name: ::buffa::alloc::string::String,
    /// Field 2: `version`
    pub version: ::buffa::alloc::string::String,
    /// Field 3: `output_module_name`
    pub output_module_name: ::buffa::alloc::string::String,
    /// Field 4: `output_module_hash`
    pub output_module_hash: ::buffa::alloc::string::String,
}
impl ::core::fmt::Debug for PackageInfo {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("PackageInfo")
            .field("name", &self.name)
            .field("version", &self.version)
            .field("output_module_name", &self.output_module_name)
            .field("output_module_hash", &self.output_module_hash)
            .finish()
    }
}
impl PackageInfo {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.PackageInfo";
}
::buffa::impl_default_instance!(PackageInfo);
impl ::buffa::MessageName for PackageInfo {
    const PACKAGE: &'static str = "sf.substreams.sink.service.v1";
    const NAME: &'static str = "PackageInfo";
    const FULL_NAME: &'static str = "sf.substreams.sink.service.v1.PackageInfo";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.PackageInfo";
}
impl ::buffa::Message for PackageInfo {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.name.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.name) as u64;
        }
        if !self.version.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.version) as u64;
        }
        if !self.output_module_name.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.output_module_name)
                        as u64;
        }
        if !self.output_module_hash.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.output_module_hash)
                        as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.name.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.name, buf);
        }
        if !self.version.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.version, buf);
        }
        if !self.output_module_name.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.output_module_name, buf);
        }
        if !self.output_module_hash.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.output_module_hash, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.name, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.version, buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.output_module_name, buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.output_module_hash, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.name.clear();
        self.version.clear();
        self.output_module_name.clear();
        self.output_module_hash.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct ListRequest {}
impl ::core::fmt::Debug for ListRequest {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("ListRequest").finish()
    }
}
impl ListRequest {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.ListRequest";
}
::buffa::impl_default_instance!(ListRequest);
impl ::buffa::MessageName for ListRequest {
    const PACKAGE: &'static str = "sf.substreams.sink.service.v1";
    const NAME: &'static str = "ListRequest";
    const FULL_NAME: &'static str = "sf.substreams.sink.service.v1.ListRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.ListRequest";
}
impl ::buffa::Message for ListRequest {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let size = 0u64;
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        _buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {}
}
#[derive(Clone, PartialEq, Default)]
pub struct ListResponse {
    /// Field 1: `deployments`
    pub deployments: ::buffa::alloc::vec::Vec<DeploymentWithStatus>,
}
impl ::core::fmt::Debug for ListResponse {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("ListResponse").field("deployments", &self.deployments).finish()
    }
}
impl ListResponse {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.ListResponse";
}
::buffa::impl_default_instance!(ListResponse);
impl ::buffa::MessageName for ListResponse {
    const PACKAGE: &'static str = "sf.substreams.sink.service.v1";
    const NAME: &'static str = "ListResponse";
    const FULL_NAME: &'static str = "sf.substreams.sink.service.v1.ListResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.ListResponse";
}
impl ::buffa::Message for ListResponse {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.deployments {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.deployments {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&elem),
                )?;
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.deployments.push(elem);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.deployments.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct DeploymentWithStatus {
    /// Field 1: `id`
    pub id: ::buffa::alloc::string::String,
    /// Field 2: `status`
    pub status: ::buffa::EnumValue<DeploymentStatus>,
    /// Field 3: `reason`
    pub reason: ::buffa::alloc::string::String,
    /// Field 4: `package_info`
    pub package_info: ::buffa::MessageField<PackageInfo, ::buffa::Inline<PackageInfo>>,
    /// Field 5: `progress`
    pub progress: ::buffa::MessageField<SinkProgress, ::buffa::Inline<SinkProgress>>,
    /// Field 6: `motd`
    pub motd: ::buffa::alloc::string::String,
}
impl ::core::fmt::Debug for DeploymentWithStatus {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("DeploymentWithStatus")
            .field("id", &self.id)
            .field("status", &self.status)
            .field("reason", &self.reason)
            .field("package_info", &self.package_info)
            .field("progress", &self.progress)
            .field("motd", &self.motd)
            .finish()
    }
}
impl DeploymentWithStatus {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.DeploymentWithStatus";
}
::buffa::impl_default_instance!(DeploymentWithStatus);
impl ::buffa::MessageName for DeploymentWithStatus {
    const PACKAGE: &'static str = "sf.substreams.sink.service.v1";
    const NAME: &'static str = "DeploymentWithStatus";
    const FULL_NAME: &'static str = "sf.substreams.sink.service.v1.DeploymentWithStatus";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.DeploymentWithStatus";
}
impl ::buffa::Message for DeploymentWithStatus {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.id.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.id) as u64;
        }
        {
            let val = self.status.to_i32();
            if val != 0 {
                size += 1u64 + ::buffa::types::int32_encoded_len(val) as u64;
            }
        }
        if !self.reason.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.reason) as u64;
        }
        if self.package_info.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.package_info.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if self.progress.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.progress.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if !self.motd.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.motd) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.id.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.id, buf);
        }
        {
            let val = self.status.to_i32();
            if val != 0 {
                ::buffa::types::put_int32_field(2u32, val, buf);
            }
        }
        if !self.reason.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.reason, buf);
        }
        if self.package_info.is_set() {
            ::buffa::types::put_len_delimited_header(
                4u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.package_info.write_to(__cache, buf);
        }
        if self.progress.is_set() {
            ::buffa::types::put_len_delimited_header(
                5u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.progress.write_to(__cache, buf);
        }
        if !self.motd.is_empty() {
            ::buffa::types::put_string_field(6u32, &self.motd, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.id, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.status = ::buffa::EnumValue::from(
                    ::buffa::types::decode_int32(buf)?,
                );
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.reason, buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.package_info.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.progress.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.motd, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.id.clear();
        self.status = ::buffa::EnumValue::from(0);
        self.reason.clear();
        self.package_info = ::buffa::MessageField::none();
        self.progress = ::buffa::MessageField::none();
        self.motd.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct RemoveRequest {
    /// Field 1: `deployment_id`
    pub deployment_id: ::buffa::alloc::string::String,
}
impl ::core::fmt::Debug for RemoveRequest {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("RemoveRequest")
            .field("deployment_id", &self.deployment_id)
            .finish()
    }
}
impl RemoveRequest {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.RemoveRequest";
}
::buffa::impl_default_instance!(RemoveRequest);
impl ::buffa::MessageName for RemoveRequest {
    const PACKAGE: &'static str = "sf.substreams.sink.service.v1";
    const NAME: &'static str = "RemoveRequest";
    const FULL_NAME: &'static str = "sf.substreams.sink.service.v1.RemoveRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.RemoveRequest";
}
impl ::buffa::Message for RemoveRequest {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.deployment_id.is_empty() {
            size
                += 1u64 + ::buffa::types::string_encoded_len(&self.deployment_id) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.deployment_id.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.deployment_id, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.deployment_id, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.deployment_id.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct RemoveResponse {
    /// Field 1: `previous_status`
    pub previous_status: ::buffa::EnumValue<DeploymentStatus>,
}
impl ::core::fmt::Debug for RemoveResponse {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("RemoveResponse")
            .field("previous_status", &self.previous_status)
            .finish()
    }
}
impl RemoveResponse {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.RemoveResponse";
}
::buffa::impl_default_instance!(RemoveResponse);
impl ::buffa::MessageName for RemoveResponse {
    const PACKAGE: &'static str = "sf.substreams.sink.service.v1";
    const NAME: &'static str = "RemoveResponse";
    const FULL_NAME: &'static str = "sf.substreams.sink.service.v1.RemoveResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.RemoveResponse";
}
impl ::buffa::Message for RemoveResponse {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        {
            let val = self.previous_status.to_i32();
            if val != 0 {
                size += 1u64 + ::buffa::types::int32_encoded_len(val) as u64;
            }
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        {
            let val = self.previous_status.to_i32();
            if val != 0 {
                ::buffa::types::put_int32_field(1u32, val, buf);
            }
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.previous_status = ::buffa::EnumValue::from(
                    ::buffa::types::decode_int32(buf)?,
                );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.previous_status = ::buffa::EnumValue::from(0);
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct PauseRequest {
    /// Field 1: `deployment_id`
    pub deployment_id: ::buffa::alloc::string::String,
}
impl ::core::fmt::Debug for PauseRequest {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("PauseRequest")
            .field("deployment_id", &self.deployment_id)
            .finish()
    }
}
impl PauseRequest {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.PauseRequest";
}
::buffa::impl_default_instance!(PauseRequest);
impl ::buffa::MessageName for PauseRequest {
    const PACKAGE: &'static str = "sf.substreams.sink.service.v1";
    const NAME: &'static str = "PauseRequest";
    const FULL_NAME: &'static str = "sf.substreams.sink.service.v1.PauseRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.PauseRequest";
}
impl ::buffa::Message for PauseRequest {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.deployment_id.is_empty() {
            size
                += 1u64 + ::buffa::types::string_encoded_len(&self.deployment_id) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.deployment_id.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.deployment_id, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.deployment_id, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.deployment_id.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct PauseResponse {
    /// Field 1: `previous_status`
    pub previous_status: ::buffa::EnumValue<DeploymentStatus>,
    /// Field 2: `new_status`
    pub new_status: ::buffa::EnumValue<DeploymentStatus>,
}
impl ::core::fmt::Debug for PauseResponse {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("PauseResponse")
            .field("previous_status", &self.previous_status)
            .field("new_status", &self.new_status)
            .finish()
    }
}
impl PauseResponse {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.PauseResponse";
}
::buffa::impl_default_instance!(PauseResponse);
impl ::buffa::MessageName for PauseResponse {
    const PACKAGE: &'static str = "sf.substreams.sink.service.v1";
    const NAME: &'static str = "PauseResponse";
    const FULL_NAME: &'static str = "sf.substreams.sink.service.v1.PauseResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.PauseResponse";
}
impl ::buffa::Message for PauseResponse {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        {
            let val = self.previous_status.to_i32();
            if val != 0 {
                size += 1u64 + ::buffa::types::int32_encoded_len(val) as u64;
            }
        }
        {
            let val = self.new_status.to_i32();
            if val != 0 {
                size += 1u64 + ::buffa::types::int32_encoded_len(val) as u64;
            }
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        {
            let val = self.previous_status.to_i32();
            if val != 0 {
                ::buffa::types::put_int32_field(1u32, val, buf);
            }
        }
        {
            let val = self.new_status.to_i32();
            if val != 0 {
                ::buffa::types::put_int32_field(2u32, val, buf);
            }
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.previous_status = ::buffa::EnumValue::from(
                    ::buffa::types::decode_int32(buf)?,
                );
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.new_status = ::buffa::EnumValue::from(
                    ::buffa::types::decode_int32(buf)?,
                );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.previous_status = ::buffa::EnumValue::from(0);
        self.new_status = ::buffa::EnumValue::from(0);
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct StopRequest {
    /// Field 1: `deployment_id`
    pub deployment_id: ::buffa::alloc::string::String,
}
impl ::core::fmt::Debug for StopRequest {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("StopRequest")
            .field("deployment_id", &self.deployment_id)
            .finish()
    }
}
impl StopRequest {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.StopRequest";
}
::buffa::impl_default_instance!(StopRequest);
impl ::buffa::MessageName for StopRequest {
    const PACKAGE: &'static str = "sf.substreams.sink.service.v1";
    const NAME: &'static str = "StopRequest";
    const FULL_NAME: &'static str = "sf.substreams.sink.service.v1.StopRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.StopRequest";
}
impl ::buffa::Message for StopRequest {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.deployment_id.is_empty() {
            size
                += 1u64 + ::buffa::types::string_encoded_len(&self.deployment_id) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.deployment_id.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.deployment_id, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.deployment_id, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.deployment_id.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct StopResponse {
    /// Field 1: `previous_status`
    pub previous_status: ::buffa::EnumValue<DeploymentStatus>,
    /// Field 2: `new_status`
    pub new_status: ::buffa::EnumValue<DeploymentStatus>,
}
impl ::core::fmt::Debug for StopResponse {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("StopResponse")
            .field("previous_status", &self.previous_status)
            .field("new_status", &self.new_status)
            .finish()
    }
}
impl StopResponse {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.StopResponse";
}
::buffa::impl_default_instance!(StopResponse);
impl ::buffa::MessageName for StopResponse {
    const PACKAGE: &'static str = "sf.substreams.sink.service.v1";
    const NAME: &'static str = "StopResponse";
    const FULL_NAME: &'static str = "sf.substreams.sink.service.v1.StopResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.StopResponse";
}
impl ::buffa::Message for StopResponse {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        {
            let val = self.previous_status.to_i32();
            if val != 0 {
                size += 1u64 + ::buffa::types::int32_encoded_len(val) as u64;
            }
        }
        {
            let val = self.new_status.to_i32();
            if val != 0 {
                size += 1u64 + ::buffa::types::int32_encoded_len(val) as u64;
            }
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        {
            let val = self.previous_status.to_i32();
            if val != 0 {
                ::buffa::types::put_int32_field(1u32, val, buf);
            }
        }
        {
            let val = self.new_status.to_i32();
            if val != 0 {
                ::buffa::types::put_int32_field(2u32, val, buf);
            }
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.previous_status = ::buffa::EnumValue::from(
                    ::buffa::types::decode_int32(buf)?,
                );
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.new_status = ::buffa::EnumValue::from(
                    ::buffa::types::decode_int32(buf)?,
                );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.previous_status = ::buffa::EnumValue::from(0);
        self.new_status = ::buffa::EnumValue::from(0);
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct ResumeRequest {
    /// Field 1: `deployment_id`
    pub deployment_id: ::buffa::alloc::string::String,
}
impl ::core::fmt::Debug for ResumeRequest {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("ResumeRequest")
            .field("deployment_id", &self.deployment_id)
            .finish()
    }
}
impl ResumeRequest {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.ResumeRequest";
}
::buffa::impl_default_instance!(ResumeRequest);
impl ::buffa::MessageName for ResumeRequest {
    const PACKAGE: &'static str = "sf.substreams.sink.service.v1";
    const NAME: &'static str = "ResumeRequest";
    const FULL_NAME: &'static str = "sf.substreams.sink.service.v1.ResumeRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.ResumeRequest";
}
impl ::buffa::Message for ResumeRequest {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.deployment_id.is_empty() {
            size
                += 1u64 + ::buffa::types::string_encoded_len(&self.deployment_id) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.deployment_id.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.deployment_id, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.deployment_id, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.deployment_id.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct ResumeResponse {
    /// Field 1: `previous_status`
    pub previous_status: ::buffa::EnumValue<DeploymentStatus>,
    /// Field 2: `new_status`
    pub new_status: ::buffa::EnumValue<DeploymentStatus>,
}
impl ::core::fmt::Debug for ResumeResponse {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("ResumeResponse")
            .field("previous_status", &self.previous_status)
            .field("new_status", &self.new_status)
            .finish()
    }
}
impl ResumeResponse {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.ResumeResponse";
}
::buffa::impl_default_instance!(ResumeResponse);
impl ::buffa::MessageName for ResumeResponse {
    const PACKAGE: &'static str = "sf.substreams.sink.service.v1";
    const NAME: &'static str = "ResumeResponse";
    const FULL_NAME: &'static str = "sf.substreams.sink.service.v1.ResumeResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.substreams.sink.service.v1.ResumeResponse";
}
impl ::buffa::Message for ResumeResponse {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        {
            let val = self.previous_status.to_i32();
            if val != 0 {
                size += 1u64 + ::buffa::types::int32_encoded_len(val) as u64;
            }
        }
        {
            let val = self.new_status.to_i32();
            if val != 0 {
                size += 1u64 + ::buffa::types::int32_encoded_len(val) as u64;
            }
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        {
            let val = self.previous_status.to_i32();
            if val != 0 {
                ::buffa::types::put_int32_field(1u32, val, buf);
            }
        }
        {
            let val = self.new_status.to_i32();
            if val != 0 {
                ::buffa::types::put_int32_field(2u32, val, buf);
            }
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.previous_status = ::buffa::EnumValue::from(
                    ::buffa::types::decode_int32(buf)?,
                );
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.new_status = ::buffa::EnumValue::from(
                    ::buffa::types::decode_int32(buf)?,
                );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.previous_status = ::buffa::EnumValue::from(0);
        self.new_status = ::buffa::EnumValue::from(0);
    }
}
