// @generated by buffa-codegen. DO NOT EDIT.

include!("sf.substreams.intern.v2.deltas.rs");
include!("sf.substreams.intern.v2.service.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.substreams.intern.v2.deltas.__view.rs");
        include!("sf.substreams.intern.v2.service.__view.rs");
        pub mod oneof {
            #[allow(unused_imports)]
            use super::*;
            include!("sf.substreams.intern.v2.deltas.__view_oneof.rs");
            include!("sf.substreams.intern.v2.service.__view_oneof.rs");
        }
    }
    pub mod lazy_view {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.substreams.intern.v2.deltas.__lazy_view.rs");
        include!("sf.substreams.intern.v2.service.__lazy_view.rs");
    }
    pub mod oneof {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.substreams.intern.v2.deltas.__oneof.rs");
        include!("sf.substreams.intern.v2.service.__oneof.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::ModuleOutputView;
#[doc(inline)]
pub use self::__buffa::view::ModuleOutputOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::ModuleOutputLazyView;
#[doc(inline)]
pub use self::__buffa::view::OperationsView;
#[doc(inline)]
pub use self::__buffa::view::OperationsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::OperationsLazyView;
#[doc(inline)]
pub use self::__buffa::view::OperationView;
#[doc(inline)]
pub use self::__buffa::view::OperationOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::OperationLazyView;
#[doc(inline)]
pub use self::__buffa::view::ProcessRangeRequestView;
#[doc(inline)]
pub use self::__buffa::view::ProcessRangeRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::ProcessRangeRequestLazyView;
#[doc(inline)]
pub use self::__buffa::view::ProcessRangeResponseView;
#[doc(inline)]
pub use self::__buffa::view::ProcessRangeResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::ProcessRangeResponseLazyView;
#[doc(inline)]
pub use self::__buffa::view::UpdateView;
#[doc(inline)]
pub use self::__buffa::view::UpdateOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::UpdateLazyView;
#[doc(inline)]
pub use self::__buffa::view::ModuleStatsView;
#[doc(inline)]
pub use self::__buffa::view::ModuleStatsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::ModuleStatsLazyView;
#[doc(inline)]
pub use self::__buffa::view::ExternalCallMetricView;
#[doc(inline)]
pub use self::__buffa::view::ExternalCallMetricOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::ExternalCallMetricLazyView;
#[doc(inline)]
pub use self::__buffa::view::CompletedView;
#[doc(inline)]
pub use self::__buffa::view::CompletedOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::CompletedLazyView;
#[doc(inline)]
pub use self::__buffa::view::FailedView;
#[doc(inline)]
pub use self::__buffa::view::FailedOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::FailedLazyView;
#[doc(inline)]
pub use self::__buffa::view::BlockRangeView;
#[doc(inline)]
pub use self::__buffa::view::BlockRangeOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::BlockRangeLazyView;
