[package]
name = "ethereum-common"
version = "0.4.0"
description = "Foundational Substreams Modules for Ethereum"
repository = "https://github.com/streamingfast/substreams-foundational-modules/ethereum-common"
edition.workspace = true
homepage.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
bench = false
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true }
hex-literal = "0.3"
num-bigint = { workspace = true }
buffa = { workspace = true }
buffa-types = { workspace = true }
substreams = { workspace = true }
substreams-ethereum = { workspace = true }

[dev-dependencies]
testing = { workspace = true }
