// @generated by buffa-codegen. DO NOT EDIT.
// source: sf/stellar/type/v1/block.proto

#[allow(non_camel_case_types)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(i32)]
pub enum TransactionStatus {
    UNKNOWN = 0i32,
    SUCCESS = 1i32,
    FAILED = 2i32,
}
impl TransactionStatus {
    ///Idiomatic alias for [`Self::UNKNOWN`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Unknown: Self = Self::UNKNOWN;
    ///Idiomatic alias for [`Self::SUCCESS`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Success: Self = Self::SUCCESS;
    ///Idiomatic alias for [`Self::FAILED`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Failed: Self = Self::FAILED;
}
impl ::core::default::Default for TransactionStatus {
    fn default() -> Self {
        Self::UNKNOWN
    }
}
impl ::buffa::Enumeration for TransactionStatus {
    fn from_i32(value: i32) -> ::core::option::Option<Self> {
        match value {
            0i32 => ::core::option::Option::Some(Self::UNKNOWN),
            1i32 => ::core::option::Option::Some(Self::SUCCESS),
            2i32 => ::core::option::Option::Some(Self::FAILED),
            _ => ::core::option::Option::None,
        }
    }
    fn to_i32(&self) -> i32 {
        *self as i32
    }
    fn proto_name(&self) -> &'static str {
        match self {
            Self::UNKNOWN => "UNKNOWN",
            Self::SUCCESS => "SUCCESS",
            Self::FAILED => "FAILED",
        }
    }
    fn from_proto_name(name: &str) -> ::core::option::Option<Self> {
        match name {
            "UNKNOWN" => ::core::option::Option::Some(Self::UNKNOWN),
            "SUCCESS" => ::core::option::Option::Some(Self::SUCCESS),
            "FAILED" => ::core::option::Option::Some(Self::FAILED),
            _ => ::core::option::Option::None,
        }
    }
    fn values() -> &'static [Self] {
        &[Self::UNKNOWN, Self::SUCCESS, Self::FAILED]
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct Block {
    /// Field 1: `number`
    pub number: u64,
    /// Field 2: `hash`
    pub hash: ::buffa::alloc::vec::Vec<u8>,
    /// Field 3: `header`
    pub header: ::buffa::MessageField<Header, ::buffa::Inline<Header>>,
    /// Field 4: `version`
    pub version: i64,
    /// Field 6: `transactions`
    pub transactions: ::buffa::alloc::vec::Vec<Transaction>,
    /// Field 9: `created_at`
    pub created_at: ::buffa::MessageField<
        ::buffa_types::google::protobuf::Timestamp,
        ::buffa::Inline<::buffa_types::google::protobuf::Timestamp>,
    >,
}
impl ::core::fmt::Debug for Block {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Block")
            .field("number", &self.number)
            .field("hash", &self.hash)
            .field("header", &self.header)
            .field("version", &self.version)
            .field("transactions", &self.transactions)
            .field("created_at", &self.created_at)
            .finish()
    }
}
impl Block {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.stellar.type.v1.Block";
}
::buffa::impl_default_instance!(Block);
impl ::buffa::MessageName for Block {
    const PACKAGE: &'static str = "sf.stellar.type.v1";
    const NAME: &'static str = "Block";
    const FULL_NAME: &'static str = "sf.stellar.type.v1.Block";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.stellar.type.v1.Block";
}
impl ::buffa::Message for Block {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.number != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.number) as u64;
        }
        if !self.hash.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.hash) as u64;
        }
        if self.header.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.header.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if self.version != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.version) as u64;
        }
        for v in &self.transactions {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if self.created_at.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.created_at.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.number != 0u64 {
            ::buffa::types::put_uint64_field(1u32, self.number, buf);
        }
        if !self.hash.is_empty() {
            ::buffa::types::put_shared_bytes_field(2u32, &self.hash, buf);
        }
        if self.header.is_set() {
            ::buffa::types::put_len_delimited_header(
                3u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.header.write_to(__cache, buf);
        }
        if self.version != 0i64 {
            ::buffa::types::put_int64_field(4u32, self.version, buf);
        }
        for v in &self.transactions {
            ::buffa::types::put_len_delimited_header(
                6u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
        if self.created_at.is_set() {
            ::buffa::types::put_len_delimited_header(
                9u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.created_at.write_to(__cache, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.number = ::buffa::types::decode_uint64(buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.hash, buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.header.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.version = ::buffa::types::decode_int64(buf)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&elem),
                )?;
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.transactions.push(elem);
            }
            9u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.created_at.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.number = 0u64;
        self.hash.clear();
        self.header = ::buffa::MessageField::none();
        self.version = 0i64;
        self.transactions.clear();
        self.created_at = ::buffa::MessageField::none();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct Header {
    /// Field 1: `ledger_version`
    pub ledger_version: u32,
    /// Field 2: `previous_ledger_hash`
    pub previous_ledger_hash: ::buffa::alloc::vec::Vec<u8>,
    /// Field 3: `total_coins`
    pub total_coins: i64,
    /// Field 4: `base_fee`
    pub base_fee: u32,
    /// Field 5: `base_reserve`
    pub base_reserve: u32,
}
impl ::core::fmt::Debug for Header {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Header")
            .field("ledger_version", &self.ledger_version)
            .field("previous_ledger_hash", &self.previous_ledger_hash)
            .field("total_coins", &self.total_coins)
            .field("base_fee", &self.base_fee)
            .field("base_reserve", &self.base_reserve)
            .finish()
    }
}
impl Header {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.stellar.type.v1.Header";
}
::buffa::impl_default_instance!(Header);
impl ::buffa::MessageName for Header {
    const PACKAGE: &'static str = "sf.stellar.type.v1";
    const NAME: &'static str = "Header";
    const FULL_NAME: &'static str = "sf.stellar.type.v1.Header";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.stellar.type.v1.Header";
}
impl ::buffa::Message for Header {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.ledger_version != 0u32 {
            size
                += 1u64 + ::buffa::types::uint32_encoded_len(self.ledger_version) as u64;
        }
        if !self.previous_ledger_hash.is_empty() {
            size
                += 1u64
                    + ::buffa::types::bytes_encoded_len(&self.previous_ledger_hash)
                        as u64;
        }
        if self.total_coins != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.total_coins) as u64;
        }
        if self.base_fee != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.base_fee) as u64;
        }
        if self.base_reserve != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.base_reserve) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.ledger_version != 0u32 {
            ::buffa::types::put_uint32_field(1u32, self.ledger_version, buf);
        }
        if !self.previous_ledger_hash.is_empty() {
            ::buffa::types::put_shared_bytes_field(
                2u32,
                &self.previous_ledger_hash,
                buf,
            );
        }
        if self.total_coins != 0i64 {
            ::buffa::types::put_int64_field(3u32, self.total_coins, buf);
        }
        if self.base_fee != 0u32 {
            ::buffa::types::put_uint32_field(4u32, self.base_fee, buf);
        }
        if self.base_reserve != 0u32 {
            ::buffa::types::put_uint32_field(5u32, self.base_reserve, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.ledger_version = ::buffa::types::decode_uint32(buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.previous_ledger_hash, buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.total_coins = ::buffa::types::decode_int64(buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.base_fee = ::buffa::types::decode_uint32(buf)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.base_reserve = ::buffa::types::decode_uint32(buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.ledger_version = 0u32;
        self.previous_ledger_hash.clear();
        self.total_coins = 0i64;
        self.base_fee = 0u32;
        self.base_reserve = 0u32;
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct Transaction {
    /// Field 1: `hash`
    pub hash: ::buffa::alloc::vec::Vec<u8>,
    /// Field 2: `status`
    pub status: ::buffa::EnumValue<TransactionStatus>,
    /// Field 3: `created_at`
    pub created_at: ::buffa::MessageField<
        ::buffa_types::google::protobuf::Timestamp,
        ::buffa::Inline<::buffa_types::google::protobuf::Timestamp>,
    >,
    /// Field 5: `application_order`
    pub application_order: u64,
    /// Field 6: `envelope_xdr`
    pub envelope_xdr: ::buffa::alloc::vec::Vec<u8>,
    /// Field 8: `result_xdr`
    pub result_xdr: ::buffa::alloc::vec::Vec<u8>,
    /// Field 9: `events`
    pub events: ::buffa::MessageField<Events, ::buffa::Inline<Events>>,
}
impl ::core::fmt::Debug for Transaction {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Transaction")
            .field("hash", &self.hash)
            .field("status", &self.status)
            .field("created_at", &self.created_at)
            .field("application_order", &self.application_order)
            .field("envelope_xdr", &self.envelope_xdr)
            .field("result_xdr", &self.result_xdr)
            .field("events", &self.events)
            .finish()
    }
}
impl Transaction {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.stellar.type.v1.Transaction";
}
::buffa::impl_default_instance!(Transaction);
impl ::buffa::MessageName for Transaction {
    const PACKAGE: &'static str = "sf.stellar.type.v1";
    const NAME: &'static str = "Transaction";
    const FULL_NAME: &'static str = "sf.stellar.type.v1.Transaction";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.stellar.type.v1.Transaction";
}
impl ::buffa::Message for Transaction {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.hash.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.hash) as u64;
        }
        {
            let val = self.status.to_i32();
            if val != 0 {
                size += 1u64 + ::buffa::types::int32_encoded_len(val) as u64;
            }
        }
        if self.created_at.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.created_at.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if self.application_order != 0u64 {
            size
                += 1u64
                    + ::buffa::types::uint64_encoded_len(self.application_order) as u64;
        }
        if !self.envelope_xdr.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.envelope_xdr) as u64;
        }
        if !self.result_xdr.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.result_xdr) as u64;
        }
        if self.events.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.events.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.hash.is_empty() {
            ::buffa::types::put_shared_bytes_field(1u32, &self.hash, buf);
        }
        {
            let val = self.status.to_i32();
            if val != 0 {
                ::buffa::types::put_int32_field(2u32, val, buf);
            }
        }
        if self.created_at.is_set() {
            ::buffa::types::put_len_delimited_header(
                3u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.created_at.write_to(__cache, buf);
        }
        if self.application_order != 0u64 {
            ::buffa::types::put_uint64_field(5u32, self.application_order, buf);
        }
        if !self.envelope_xdr.is_empty() {
            ::buffa::types::put_shared_bytes_field(6u32, &self.envelope_xdr, buf);
        }
        if !self.result_xdr.is_empty() {
            ::buffa::types::put_shared_bytes_field(8u32, &self.result_xdr, buf);
        }
        if self.events.is_set() {
            ::buffa::types::put_len_delimited_header(
                9u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.events.write_to(__cache, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.hash, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.status = ::buffa::EnumValue::from(
                    ::buffa::types::decode_int32(buf)?,
                );
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.created_at.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.application_order = ::buffa::types::decode_uint64(buf)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.envelope_xdr, buf)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.result_xdr, buf)?;
            }
            9u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.events.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.hash.clear();
        self.status = ::buffa::EnumValue::from(0);
        self.created_at = ::buffa::MessageField::none();
        self.application_order = 0u64;
        self.envelope_xdr.clear();
        self.result_xdr.clear();
        self.events = ::buffa::MessageField::none();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct Events {
    /// Field 1: `diagnostic_events_xdr`
    pub diagnostic_events_xdr: ::buffa::alloc::vec::Vec<::buffa::alloc::vec::Vec<u8>>,
    /// Field 2: `transaction_events_xdr`
    pub transaction_events_xdr: ::buffa::alloc::vec::Vec<::buffa::alloc::vec::Vec<u8>>,
    /// Field 3: `contract_events_xdr`
    pub contract_events_xdr: ::buffa::alloc::vec::Vec<ContractEvent>,
}
impl ::core::fmt::Debug for Events {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Events")
            .field("diagnostic_events_xdr", &self.diagnostic_events_xdr)
            .field("transaction_events_xdr", &self.transaction_events_xdr)
            .field("contract_events_xdr", &self.contract_events_xdr)
            .finish()
    }
}
impl Events {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.stellar.type.v1.Events";
}
::buffa::impl_default_instance!(Events);
impl ::buffa::MessageName for Events {
    const PACKAGE: &'static str = "sf.stellar.type.v1";
    const NAME: &'static str = "Events";
    const FULL_NAME: &'static str = "sf.stellar.type.v1.Events";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.stellar.type.v1.Events";
}
impl ::buffa::Message for Events {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.diagnostic_events_xdr {
            size += 1u64 + ::buffa::types::bytes_encoded_len(v) as u64;
        }
        for v in &self.transaction_events_xdr {
            size += 1u64 + ::buffa::types::bytes_encoded_len(v) as u64;
        }
        for v in &self.contract_events_xdr {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.diagnostic_events_xdr {
            ::buffa::types::put_shared_bytes_field(1u32, v, buf);
        }
        for v in &self.transaction_events_xdr {
            ::buffa::types::put_shared_bytes_field(2u32, v, buf);
        }
        for v in &self.contract_events_xdr {
            ::buffa::types::put_len_delimited_header(
                3u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __elem = ::buffa::types::decode_bytes(buf)?;
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&__elem),
                )?;
                self.diagnostic_events_xdr.push(__elem);
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __elem = ::buffa::types::decode_bytes(buf)?;
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&__elem),
                )?;
                self.transaction_events_xdr.push(__elem);
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&elem),
                )?;
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.contract_events_xdr.push(elem);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.diagnostic_events_xdr.clear();
        self.transaction_events_xdr.clear();
        self.contract_events_xdr.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct ContractEvent {
    /// Field 1: `events`
    pub events: ::buffa::alloc::vec::Vec<::buffa::alloc::vec::Vec<u8>>,
}
impl ::core::fmt::Debug for ContractEvent {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("ContractEvent").field("events", &self.events).finish()
    }
}
impl ContractEvent {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.stellar.type.v1.ContractEvent";
}
::buffa::impl_default_instance!(ContractEvent);
impl ::buffa::MessageName for ContractEvent {
    const PACKAGE: &'static str = "sf.stellar.type.v1";
    const NAME: &'static str = "ContractEvent";
    const FULL_NAME: &'static str = "sf.stellar.type.v1.ContractEvent";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.stellar.type.v1.ContractEvent";
}
impl ::buffa::Message for ContractEvent {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.events {
            size += 1u64 + ::buffa::types::bytes_encoded_len(v) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.events {
            ::buffa::types::put_shared_bytes_field(1u32, v, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __elem = ::buffa::types::decode_bytes(buf)?;
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&__elem),
                )?;
                self.events.push(__elem);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.events.clear();
    }
}
