// @generated by buffa-codegen. DO NOT EDIT.
// source: types.proto

pub mod operation {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, PartialEq, Debug)]
    #[allow(clippy::large_enum_variant)]
    pub enum Op {
        CreateAccount(super::super::super::CreateAccount),
        AccountMerge(super::super::super::AccountMerge),
        Payment(super::super::super::Payment),
        CreateClaimableBalance(super::super::super::CreateClaimableBalance),
        ClaimClaimableBalance(super::super::super::ClaimClaimableBalance),
        Clawback(super::super::super::Clawback),
        ClawbackClaimableBalance(super::super::super::ClawbackClaimableBalance),
        AllowTrust(super::super::super::AllowTrust),
        SetTrustLineFlags(super::super::super::SetTrustLineFlags),
        LiquidityPoolDeposit(super::super::super::LiquidityPoolDeposit),
        LiquidityPoolWithdraw(super::super::super::LiquidityPoolWithdraw),
        ManageBuyOffer(super::super::super::ManageBuyOffer),
        ManageSellOffer(super::super::super::ManageSellOffer),
        CreatePassiveSellOffer(super::super::super::CreatePassiveSellOffer),
        PathPaymentStrictSend(super::super::super::PathPaymentStrictSend),
        PathPaymentStrictReceive(super::super::super::PathPaymentStrictReceive),
    }
    impl ::buffa::Oneof for Op {}
    impl From<super::super::super::CreateAccount> for Op {
        fn from(v: super::super::super::CreateAccount) -> Self {
            Self::CreateAccount(v)
        }
    }
    impl From<super::super::super::CreateAccount> for ::core::option::Option<Op> {
        fn from(v: super::super::super::CreateAccount) -> Self {
            Self::Some(Op::from(v))
        }
    }
    impl From<super::super::super::AccountMerge> for Op {
        fn from(v: super::super::super::AccountMerge) -> Self {
            Self::AccountMerge(v)
        }
    }
    impl From<super::super::super::AccountMerge> for ::core::option::Option<Op> {
        fn from(v: super::super::super::AccountMerge) -> Self {
            Self::Some(Op::from(v))
        }
    }
    impl From<super::super::super::Payment> for Op {
        fn from(v: super::super::super::Payment) -> Self {
            Self::Payment(v)
        }
    }
    impl From<super::super::super::Payment> for ::core::option::Option<Op> {
        fn from(v: super::super::super::Payment) -> Self {
            Self::Some(Op::from(v))
        }
    }
    impl From<super::super::super::CreateClaimableBalance> for Op {
        fn from(v: super::super::super::CreateClaimableBalance) -> Self {
            Self::CreateClaimableBalance(v)
        }
    }
    impl From<super::super::super::CreateClaimableBalance>
    for ::core::option::Option<Op> {
        fn from(v: super::super::super::CreateClaimableBalance) -> Self {
            Self::Some(Op::from(v))
        }
    }
    impl From<super::super::super::ClaimClaimableBalance> for Op {
        fn from(v: super::super::super::ClaimClaimableBalance) -> Self {
            Self::ClaimClaimableBalance(v)
        }
    }
    impl From<super::super::super::ClaimClaimableBalance>
    for ::core::option::Option<Op> {
        fn from(v: super::super::super::ClaimClaimableBalance) -> Self {
            Self::Some(Op::from(v))
        }
    }
    impl From<super::super::super::Clawback> for Op {
        fn from(v: super::super::super::Clawback) -> Self {
            Self::Clawback(v)
        }
    }
    impl From<super::super::super::Clawback> for ::core::option::Option<Op> {
        fn from(v: super::super::super::Clawback) -> Self {
            Self::Some(Op::from(v))
        }
    }
    impl From<super::super::super::ClawbackClaimableBalance> for Op {
        fn from(v: super::super::super::ClawbackClaimableBalance) -> Self {
            Self::ClawbackClaimableBalance(v)
        }
    }
    impl From<super::super::super::ClawbackClaimableBalance>
    for ::core::option::Option<Op> {
        fn from(v: super::super::super::ClawbackClaimableBalance) -> Self {
            Self::Some(Op::from(v))
        }
    }
    impl From<super::super::super::AllowTrust> for Op {
        fn from(v: super::super::super::AllowTrust) -> Self {
            Self::AllowTrust(v)
        }
    }
    impl From<super::super::super::AllowTrust> for ::core::option::Option<Op> {
        fn from(v: super::super::super::AllowTrust) -> Self {
            Self::Some(Op::from(v))
        }
    }
    impl From<super::super::super::SetTrustLineFlags> for Op {
        fn from(v: super::super::super::SetTrustLineFlags) -> Self {
            Self::SetTrustLineFlags(v)
        }
    }
    impl From<super::super::super::SetTrustLineFlags> for ::core::option::Option<Op> {
        fn from(v: super::super::super::SetTrustLineFlags) -> Self {
            Self::Some(Op::from(v))
        }
    }
    impl From<super::super::super::LiquidityPoolDeposit> for Op {
        fn from(v: super::super::super::LiquidityPoolDeposit) -> Self {
            Self::LiquidityPoolDeposit(v)
        }
    }
    impl From<super::super::super::LiquidityPoolDeposit> for ::core::option::Option<Op> {
        fn from(v: super::super::super::LiquidityPoolDeposit) -> Self {
            Self::Some(Op::from(v))
        }
    }
    impl From<super::super::super::LiquidityPoolWithdraw> for Op {
        fn from(v: super::super::super::LiquidityPoolWithdraw) -> Self {
            Self::LiquidityPoolWithdraw(v)
        }
    }
    impl From<super::super::super::LiquidityPoolWithdraw>
    for ::core::option::Option<Op> {
        fn from(v: super::super::super::LiquidityPoolWithdraw) -> Self {
            Self::Some(Op::from(v))
        }
    }
    impl From<super::super::super::ManageBuyOffer> for Op {
        fn from(v: super::super::super::ManageBuyOffer) -> Self {
            Self::ManageBuyOffer(v)
        }
    }
    impl From<super::super::super::ManageBuyOffer> for ::core::option::Option<Op> {
        fn from(v: super::super::super::ManageBuyOffer) -> Self {
            Self::Some(Op::from(v))
        }
    }
    impl From<super::super::super::ManageSellOffer> for Op {
        fn from(v: super::super::super::ManageSellOffer) -> Self {
            Self::ManageSellOffer(v)
        }
    }
    impl From<super::super::super::ManageSellOffer> for ::core::option::Option<Op> {
        fn from(v: super::super::super::ManageSellOffer) -> Self {
            Self::Some(Op::from(v))
        }
    }
    impl From<super::super::super::CreatePassiveSellOffer> for Op {
        fn from(v: super::super::super::CreatePassiveSellOffer) -> Self {
            Self::CreatePassiveSellOffer(v)
        }
    }
    impl From<super::super::super::CreatePassiveSellOffer>
    for ::core::option::Option<Op> {
        fn from(v: super::super::super::CreatePassiveSellOffer) -> Self {
            Self::Some(Op::from(v))
        }
    }
    impl From<super::super::super::PathPaymentStrictSend> for Op {
        fn from(v: super::super::super::PathPaymentStrictSend) -> Self {
            Self::PathPaymentStrictSend(v)
        }
    }
    impl From<super::super::super::PathPaymentStrictSend>
    for ::core::option::Option<Op> {
        fn from(v: super::super::super::PathPaymentStrictSend) -> Self {
            Self::Some(Op::from(v))
        }
    }
    impl From<super::super::super::PathPaymentStrictReceive> for Op {
        fn from(v: super::super::super::PathPaymentStrictReceive) -> Self {
            Self::PathPaymentStrictReceive(v)
        }
    }
    impl From<super::super::super::PathPaymentStrictReceive>
    for ::core::option::Option<Op> {
        fn from(v: super::super::super::PathPaymentStrictReceive) -> Self {
            Self::Some(Op::from(v))
        }
    }
}
pub mod asset {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, PartialEq, Debug)]
    #[allow(clippy::large_enum_variant)]
    pub enum Asset {
        Native(::buffa::alloc::string::String),
        CreditAlphaNum4(super::super::super::CreditAlphaNum4),
        CreditAlphaNum12(super::super::super::CreditAlphaNum12),
    }
    impl ::buffa::Oneof for Asset {}
    impl From<super::super::super::CreditAlphaNum4> for Asset {
        fn from(v: super::super::super::CreditAlphaNum4) -> Self {
            Self::CreditAlphaNum4(v)
        }
    }
    impl From<super::super::super::CreditAlphaNum4> for ::core::option::Option<Asset> {
        fn from(v: super::super::super::CreditAlphaNum4) -> Self {
            Self::Some(Asset::from(v))
        }
    }
    impl From<super::super::super::CreditAlphaNum12> for Asset {
        fn from(v: super::super::super::CreditAlphaNum12) -> Self {
            Self::CreditAlphaNum12(v)
        }
    }
    impl From<super::super::super::CreditAlphaNum12> for ::core::option::Option<Asset> {
        fn from(v: super::super::super::CreditAlphaNum12) -> Self {
            Self::Some(Asset::from(v))
        }
    }
}
