// @generated by buffa-codegen. DO NOT EDIT.
// source: types.proto

pub mod operation {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, Debug)]
    pub enum Op<'a> {
        CreateAccount(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::CreateAccountView<'a>,
            >,
        ),
        AccountMerge(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::AccountMergeView<'a>,
            >,
        ),
        Payment(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::PaymentView<'a>,
            >,
        ),
        CreateClaimableBalance(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::CreateClaimableBalanceView<'a>,
            >,
        ),
        ClaimClaimableBalance(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::ClaimClaimableBalanceView<'a>,
            >,
        ),
        Clawback(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::ClawbackView<'a>,
            >,
        ),
        ClawbackClaimableBalance(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::ClawbackClaimableBalanceView<
                    'a,
                >,
            >,
        ),
        AllowTrust(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::AllowTrustView<'a>,
            >,
        ),
        SetTrustLineFlags(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::SetTrustLineFlagsView<'a>,
            >,
        ),
        LiquidityPoolDeposit(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::LiquidityPoolDepositView<'a>,
            >,
        ),
        LiquidityPoolWithdraw(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::LiquidityPoolWithdrawView<'a>,
            >,
        ),
        ManageBuyOffer(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::ManageBuyOfferView<'a>,
            >,
        ),
        ManageSellOffer(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::ManageSellOfferView<'a>,
            >,
        ),
        CreatePassiveSellOffer(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::CreatePassiveSellOfferView<'a>,
            >,
        ),
        PathPaymentStrictSend(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::PathPaymentStrictSendView<'a>,
            >,
        ),
        PathPaymentStrictReceive(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::PathPaymentStrictReceiveView<
                    'a,
                >,
            >,
        ),
    }
}
pub mod asset {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, Debug)]
    pub enum Asset<'a> {
        Native(&'a str),
        CreditAlphaNum4(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::CreditAlphaNum4View<'a>,
            >,
        ),
        CreditAlphaNum12(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::CreditAlphaNum12View<'a>,
            >,
        ),
    }
}
