// @generated by buffa-codegen. DO NOT EDIT.

include!("erc20-metadata.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("erc20-metadata.__view.rs");
    }
    pub mod lazy_view {
        #[allow(unused_imports)]
        use super::*;
        include!("erc20-metadata.__lazy_view.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::EventsView;
#[doc(inline)]
pub use self::__buffa::view::EventsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::EventsLazyView;
#[doc(inline)]
pub use self::__buffa::view::MetadataInitializeView;
#[doc(inline)]
pub use self::__buffa::view::MetadataInitializeOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::MetadataInitializeLazyView;
#[doc(inline)]
pub use self::__buffa::view::MetadataChangesView;
#[doc(inline)]
pub use self::__buffa::view::MetadataChangesOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::MetadataChangesLazyView;
