// @generated by buffa-codegen. DO NOT EDIT.

include!("v1.erc20-stores.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("v1.erc20-stores.__view.rs");
    }
    pub mod lazy_view {
        #[allow(unused_imports)]
        use super::*;
        include!("v1.erc20-stores.__lazy_view.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::EventsView;
#[doc(inline)]
pub use self::__buffa::view::EventsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::EventsLazyView;
#[doc(inline)]
pub use self::__buffa::view::FirstTransferByContractView;
#[doc(inline)]
pub use self::__buffa::view::FirstTransferByContractOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::FirstTransferByContractLazyView;
