// @generated by buffa-codegen. DO NOT EDIT.

include!("sf.substreams.intern.v2.deltas.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.substreams.intern.v2.deltas.__view.rs");
        pub mod oneof {
            #[allow(unused_imports)]
            use super::*;
            include!("sf.substreams.intern.v2.deltas.__view_oneof.rs");
        }
    }
    pub mod lazy_view {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.substreams.intern.v2.deltas.__lazy_view.rs");
    }
    pub mod oneof {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.substreams.intern.v2.deltas.__oneof.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::ModuleOutputView;
#[doc(inline)]
pub use self::__buffa::view::ModuleOutputOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::ModuleOutputLazyView;
#[doc(inline)]
pub use self::__buffa::view::OperationsView;
#[doc(inline)]
pub use self::__buffa::view::OperationsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::OperationsLazyView;
#[doc(inline)]
pub use self::__buffa::view::OperationView;
#[doc(inline)]
pub use self::__buffa::view::OperationOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::OperationLazyView;
