// @generated by buffa-codegen. DO NOT EDIT.
// source: v1/erc20-transfers.proto

/** Lazy view of `evm.erc20.transfers.v1.Events`: nested and repeated message fields are
 recorded as undecoded byte ranges and decoded on access. See
 [`::buffa::LazyMessageView`] for the deferred-validation contract;
 the eager, whole-tree-validated counterpart is named `EventsView`.

 Oneof variants, map values, groups, and extern-typed fields (e.g.
 well-known types) hold eagerly-decoded `EventsView`-family
 types; only singular/repeated message fields defer.

 # Examples

 ```rust,ignore
 use buffa::LazyMessageView;

 let view = EventsLazyView::decode_lazy(&bytes)?;
 ```*/
#[derive(Clone, Debug, Default)]
pub struct EventsLazyView<'a> {
    /// <https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/IERC20.sol>
    ///
    /// Field 1: `transfers`
    pub transfers: ::buffa::LazyRepeatedView<
        'a,
        super::super::__buffa::lazy_view::TransferLazyView<'a>,
    >,
    /// Field 2: `approvals`
    pub approvals: ::buffa::LazyRepeatedView<
        'a,
        super::super::__buffa::lazy_view::ApprovalLazyView<'a>,
    >,
}
impl<'a> EventsLazyView<'a> {
    /// Decode from `buf` under the limits carried by `ctx`, recording
    /// nested/repeated message fields as byte ranges.
    ///
    /// **Not part of the public API.**
    #[doc(hidden)]
    pub fn _decode_lazy_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let mut view = Self::default();
        view._merge_lazy(buf, ctx)?;
        ::core::result::Result::Ok(view)
    }
    /// Merge fields from `buf` into this view (proto merge semantics;
    /// deferred message fragments accumulate).
    ///
    /// **Not part of the public API.**
    #[doc(hidden)]
    pub fn _merge_lazy(
        &mut self,
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur: &'a [u8] = buf;
        while !cur.is_empty() {
            let tag = ::buffa::encoding::Tag::decode(&mut cur)?;
            match tag.field_number() {
                1u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::LengthDelimited,
                    )?;
                    let __sub_ctx = ctx.descend()?;
                    let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                    ctx.register_element_memory(::core::mem::size_of::<&'a [u8]>())?;
                    view.transfers.push_bytes(sub, __sub_ctx);
                }
                2u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::LengthDelimited,
                    )?;
                    let __sub_ctx = ctx.descend()?;
                    let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                    ctx.register_element_memory(::core::mem::size_of::<&'a [u8]>())?;
                    view.approvals.push_bytes(sub, __sub_ctx);
                }
                _ => {
                    ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
                }
            }
        }
        ::core::result::Result::Ok(())
    }
}
impl<'a> ::buffa::LazyMessageView<'a> for EventsLazyView<'a> {
    type Owned = super::super::Events;
    fn decode_lazy(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        Self::_decode_lazy_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_lazy_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        Self::_decode_lazy_ctx(buf, ctx)
    }
    fn merge_lazy(
        &mut self,
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        self._merge_lazy(buf, ctx)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Events, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        #[allow(unused_imports)]
        use ::buffa::MessageView as _;
        let __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes> = ::core::option::Option::None;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Events {
            transfers: {
                let mut __out = ::buffa::alloc::vec::Vec::with_capacity(
                    self.transfers.len(),
                );
                for __r in self.transfers.iter() {
                    __out.push(__r?.to_owned_message()?);
                }
                __out
            },
            approvals: {
                let mut __out = ::buffa::alloc::vec::Vec::with_capacity(
                    self.approvals.len(),
                );
                for __r in self.approvals.iter() {
                    __out.push(__r?.to_owned_message()?);
                }
                __out
            },
            ..::core::default::Default::default()
        })
    }
}
/// Re-encoding: recorded fragments are replayed byte-for-byte
/// **without validation** — wire-equivalent to the merged value, and
/// a never-accessed malformed deferred field round-trips silently.
/// Inherent rather than [`::buffa::ViewEncode`] (whose `MessageView`
/// supertrait carries the eager whole-tree-validated contract); the
/// fuller `ViewEncode` set (`encode_length_delimited`,
/// `encode_with_cache`) lives on the eager view.
impl<'a> EventsLazyView<'a> {
    /// Compute the encoded byte size, filling `cache` with
    /// per-message sizes consumed by a following `write_to` call.
    /// Called for that side effect by `encode`; prefer `encoded_len`
    /// when only the size is needed.
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    pub fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        #[allow(unused_imports)]
        use ::buffa::ViewEncode as _;
        let mut size = 0u64;
        for __frag in self.transfers.raw_elements() {
            size
                += 1u64 + ::buffa::encoding::varint_len(__frag.len() as u64) as u64
                    + __frag.len() as u64;
        }
        for __frag in self.approvals.raw_elements() {
            size
                += 1u64 + ::buffa::encoding::varint_len(__frag.len() as u64) as u64
                    + __frag.len() as u64;
        }
        ::buffa::saturate_size(size)
    }
    /// Write the encoded bytes to `buf`, reading per-message sizes
    /// from the `cache` filled by a preceding `compute_size` call.
    /// Prefer `encode` unless threading a shared cache.
    #[allow(clippy::needless_borrow)]
    pub fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        #[allow(unused_imports)]
        use ::buffa::ViewEncode as _;
        for __frag in self.transfers.raw_elements() {
            ::buffa::encoding::Tag::new(
                    1u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::encoding::encode_varint(__frag.len() as u64, buf);
            buf.put_slice(__frag);
        }
        for __frag in self.approvals.raw_elements() {
            ::buffa::encoding::Tag::new(
                    2u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::encoding::encode_varint(__frag.len() as u64, buf);
            buf.put_slice(__frag);
        }
    }
    /// Compute size, then write. Primary encode entry point.
    ///
    /// # Panics
    ///
    /// Panics if the encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]) — see
    /// [`try_encode`](Self::try_encode) for the error-returning
    /// variant.
    #[inline]
    pub fn encode(&self, buf: &mut impl ::buffa::EncodeSink) {
        self.try_encode(buf).unwrap_or_else(|_| ::buffa::encode_size_overflow())
    }
    /// Encode, returning an error instead of panicking if the
    /// encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]).
    ///
    /// On `Err`, nothing is written to `buf`.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::EncodeError::MessageTooLarge`] if the
    /// encoded size exceeds the limit.
    pub fn try_encode(
        &self,
        buf: &mut impl ::buffa::EncodeSink,
    ) -> ::core::result::Result<(), ::buffa::EncodeError> {
        let mut __cache = ::buffa::SizeCache::new();
        ::buffa::checked_encode_size(self.compute_size(&mut __cache))?;
        self.write_to(&mut __cache, buf);
        ::core::result::Result::Ok(())
    }
    /// Encoded byte size of this view.
    ///
    /// # Panics
    ///
    /// Panics if the encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]) — see
    /// [`try_encoded_len`](Self::try_encoded_len) for the
    /// error-returning variant.
    #[inline]
    #[must_use]
    pub fn encoded_len(&self) -> u32 {
        self.try_encoded_len().unwrap_or_else(|_| ::buffa::encode_size_overflow())
    }
    /// Encoded byte size, returning an error instead of panicking
    /// if it exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::EncodeError::MessageTooLarge`] if the
    /// encoded size exceeds the limit.
    pub fn try_encoded_len(&self) -> ::core::result::Result<u32, ::buffa::EncodeError> {
        ::buffa::checked_encode_size(self.compute_size(&mut ::buffa::SizeCache::new()))
    }
    /// Encode this view to a new `Vec<u8>`.
    ///
    /// # Panics
    ///
    /// Panics if the encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]) — see
    /// [`try_encode_to_vec`](Self::try_encode_to_vec) for the
    /// error-returning variant. In debug builds, also panics if the
    /// two encode passes disagree on the byte count.
    #[inline]
    #[must_use]
    pub fn encode_to_vec(&self) -> ::buffa::alloc::vec::Vec<u8> {
        let mut __cache = ::buffa::SizeCache::new();
        let __size = match ::buffa::checked_encode_size(
            self.compute_size(&mut __cache),
        ) {
            ::core::result::Result::Ok(__size) => __size as usize,
            ::core::result::Result::Err(_) => ::buffa::encode_size_overflow(),
        };
        let mut __buf = ::buffa::alloc::vec::Vec::with_capacity(__size);
        self.write_to(&mut __cache, &mut __buf);
        ::buffa::debug_assert_two_pass(__buf.len(), __size);
        __buf
    }
    /// Encode to a new `Vec<u8>`, returning an error instead of
    /// panicking if the encoded size exceeds the 2 GiB protobuf
    /// limit ([`::buffa::MAX_MESSAGE_BYTES`]).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::EncodeError::MessageTooLarge`] if the
    /// encoded size exceeds the limit.
    ///
    /// # Panics
    ///
    /// In debug builds, panics if the two encode passes disagree
    /// on the byte count.
    pub fn try_encode_to_vec(
        &self,
    ) -> ::core::result::Result<::buffa::alloc::vec::Vec<u8>, ::buffa::EncodeError> {
        let mut __cache = ::buffa::SizeCache::new();
        let __size = ::buffa::checked_encode_size(self.compute_size(&mut __cache))?
            as usize;
        let mut __buf = ::buffa::alloc::vec::Vec::with_capacity(__size);
        self.write_to(&mut __cache, &mut __buf);
        ::buffa::debug_assert_two_pass(__buf.len(), __size);
        ::core::result::Result::Ok(__buf)
    }
    /// Encode this view to a new [`::buffa::bytes::Bytes`].
    ///
    /// # Panics
    ///
    /// Panics if the encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]) — see
    /// [`try_encode_to_bytes`](Self::try_encode_to_bytes) for the
    /// error-returning variant. In debug builds, also panics if the
    /// two encode passes disagree on the byte count.
    #[inline]
    #[must_use]
    pub fn encode_to_bytes(&self) -> ::buffa::bytes::Bytes {
        let mut __cache = ::buffa::SizeCache::new();
        let __size = match ::buffa::checked_encode_size(
            self.compute_size(&mut __cache),
        ) {
            ::core::result::Result::Ok(__size) => __size as usize,
            ::core::result::Result::Err(_) => ::buffa::encode_size_overflow(),
        };
        let mut __buf = ::buffa::bytes::BytesMut::with_capacity(__size);
        self.write_to(&mut __cache, &mut __buf);
        ::buffa::debug_assert_two_pass(__buf.len(), __size);
        __buf.freeze()
    }
    /// Encode to a new [`::buffa::bytes::Bytes`], returning an
    /// error instead of panicking if the encoded size exceeds the
    /// 2 GiB protobuf limit ([`::buffa::MAX_MESSAGE_BYTES`]).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::EncodeError::MessageTooLarge`] if the
    /// encoded size exceeds the limit.
    ///
    /// # Panics
    ///
    /// In debug builds, panics if the two encode passes disagree
    /// on the byte count.
    pub fn try_encode_to_bytes(
        &self,
    ) -> ::core::result::Result<::buffa::bytes::Bytes, ::buffa::EncodeError> {
        let mut __cache = ::buffa::SizeCache::new();
        let __size = ::buffa::checked_encode_size(self.compute_size(&mut __cache))?
            as usize;
        let mut __buf = ::buffa::bytes::BytesMut::with_capacity(__size);
        self.write_to(&mut __cache, &mut __buf);
        ::buffa::debug_assert_two_pass(__buf.len(), __size);
        ::core::result::Result::Ok(__buf.freeze())
    }
}
impl<'a> ::buffa::MessageName for EventsLazyView<'a> {
    const PACKAGE: &'static str = "evm.erc20.transfers.v1";
    const NAME: &'static str = "Events";
    const FULL_NAME: &'static str = "evm.erc20.transfers.v1.Events";
    const TYPE_URL: &'static str = "type.googleapis.com/evm.erc20.transfers.v1.Events";
}
/** Lazy view of `evm.erc20.transfers.v1.Transfer`: nested and repeated message fields are
 recorded as undecoded byte ranges and decoded on access. See
 [`::buffa::LazyMessageView`] for the deferred-validation contract;
 the eager, whole-tree-validated counterpart is named `TransferView`.

 Oneof variants, map values, groups, and extern-typed fields (e.g.
 well-known types) hold eagerly-decoded `TransferView`-family
 types; only singular/repeated message fields defer.

 # Examples

 ```rust,ignore
 use buffa::LazyMessageView;

 let view = TransferLazyView::decode_lazy(&bytes)?;
 ```*/
#[derive(Clone, Debug, Default)]
pub struct TransferLazyView<'a> {
    /// -- transaction --
    ///
    /// Field 1: `tx_hash`
    pub tx_hash: &'a [u8],
    /// -- call --
    ///
    /// Field 2: `caller`
    pub caller: ::core::option::Option<&'a [u8]>,
    /// -- log --
    ///
    /// log.address
    ///
    /// Field 3: `contract`
    pub contract: &'a [u8],
    /// log.ordinal
    ///
    /// Field 4: `ordinal`
    pub ordinal: u64,
    /// log.index
    ///
    /// Field 5: `log_index`
    pub log_index: u32,
    /// -- event --
    ///
    /// Field 10: `from`
    pub from: &'a [u8],
    /// Field 11: `to`
    pub to: &'a [u8],
    /// Field 12: `value`
    pub value: &'a str,
}
impl<'a> TransferLazyView<'a> {
    /// Decode from `buf` under the limits carried by `ctx`, recording
    /// nested/repeated message fields as byte ranges.
    ///
    /// **Not part of the public API.**
    #[doc(hidden)]
    pub fn _decode_lazy_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let mut view = Self::default();
        view._merge_lazy(buf, ctx)?;
        ::core::result::Result::Ok(view)
    }
    /// Merge fields from `buf` into this view (proto merge semantics;
    /// deferred message fragments accumulate).
    ///
    /// **Not part of the public API.**
    #[doc(hidden)]
    pub fn _merge_lazy(
        &mut self,
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur: &'a [u8] = buf;
        while !cur.is_empty() {
            let tag = ::buffa::encoding::Tag::decode(&mut cur)?;
            match tag.field_number() {
                1u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::LengthDelimited,
                    )?;
                    view.tx_hash = ::buffa::types::borrow_bytes(&mut cur)?;
                }
                2u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::LengthDelimited,
                    )?;
                    view.caller = Some(::buffa::types::borrow_bytes(&mut cur)?);
                }
                3u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::LengthDelimited,
                    )?;
                    view.contract = ::buffa::types::borrow_bytes(&mut cur)?;
                }
                4u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::Varint,
                    )?;
                    view.ordinal = ::buffa::types::decode_uint64(&mut cur)?;
                }
                5u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::Varint,
                    )?;
                    view.log_index = ::buffa::types::decode_uint32(&mut cur)?;
                }
                10u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::LengthDelimited,
                    )?;
                    view.from = ::buffa::types::borrow_bytes(&mut cur)?;
                }
                11u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::LengthDelimited,
                    )?;
                    view.to = ::buffa::types::borrow_bytes(&mut cur)?;
                }
                12u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::LengthDelimited,
                    )?;
                    view.value = ::buffa::types::borrow_str(&mut cur)?;
                }
                _ => {
                    ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
                }
            }
        }
        ::core::result::Result::Ok(())
    }
}
impl<'a> ::buffa::LazyMessageView<'a> for TransferLazyView<'a> {
    type Owned = super::super::Transfer;
    fn decode_lazy(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        Self::_decode_lazy_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_lazy_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        Self::_decode_lazy_ctx(buf, ctx)
    }
    fn merge_lazy(
        &mut self,
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        self._merge_lazy(buf, ctx)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Transfer, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        #[allow(unused_imports)]
        use ::buffa::MessageView as _;
        let __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes> = ::core::option::Option::None;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Transfer {
            tx_hash: (self.tx_hash).to_vec(),
            caller: self.caller.map(|b| (b).to_vec()),
            contract: (self.contract).to_vec(),
            ordinal: self.ordinal,
            log_index: self.log_index,
            from: (self.from).to_vec(),
            to: (self.to).to_vec(),
            value: self.value.to_string(),
            ..::core::default::Default::default()
        })
    }
}
/// Re-encoding: recorded fragments are replayed byte-for-byte
/// **without validation** — wire-equivalent to the merged value, and
/// a never-accessed malformed deferred field round-trips silently.
/// Inherent rather than [`::buffa::ViewEncode`] (whose `MessageView`
/// supertrait carries the eager whole-tree-validated contract); the
/// fuller `ViewEncode` set (`encode_length_delimited`,
/// `encode_with_cache`) lives on the eager view.
impl<'a> TransferLazyView<'a> {
    /// Compute the encoded byte size, filling `cache` with
    /// per-message sizes consumed by a following `write_to` call.
    /// Called for that side effect by `encode`; prefer `encoded_len`
    /// when only the size is needed.
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    pub fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        #[allow(unused_imports)]
        use ::buffa::ViewEncode as _;
        let mut size = 0u64;
        if !self.tx_hash.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.tx_hash) as u64;
        }
        if let Some(ref v) = self.caller {
            size += 1u64 + ::buffa::types::bytes_encoded_len(v) as u64;
        }
        if !self.contract.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.contract) as u64;
        }
        if self.ordinal != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.ordinal) as u64;
        }
        if self.log_index != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.log_index) as u64;
        }
        if !self.from.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.from) as u64;
        }
        if !self.to.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.to) as u64;
        }
        if !self.value.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.value) as u64;
        }
        ::buffa::saturate_size(size)
    }
    /// Write the encoded bytes to `buf`, reading per-message sizes
    /// from the `cache` filled by a preceding `compute_size` call.
    /// Prefer `encode` unless threading a shared cache.
    #[allow(clippy::needless_borrow)]
    pub fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        #[allow(unused_imports)]
        use ::buffa::ViewEncode as _;
        if !self.tx_hash.is_empty() {
            ::buffa::types::put_shared_bytes_field(1u32, &self.tx_hash, buf);
        }
        if let Some(ref v) = self.caller {
            ::buffa::types::put_shared_bytes_field(2u32, v, buf);
        }
        if !self.contract.is_empty() {
            ::buffa::types::put_shared_bytes_field(3u32, &self.contract, buf);
        }
        if self.ordinal != 0u64 {
            ::buffa::types::put_uint64_field(4u32, self.ordinal, buf);
        }
        if self.log_index != 0u32 {
            ::buffa::types::put_uint32_field(5u32, self.log_index, buf);
        }
        if !self.from.is_empty() {
            ::buffa::types::put_shared_bytes_field(10u32, &self.from, buf);
        }
        if !self.to.is_empty() {
            ::buffa::types::put_shared_bytes_field(11u32, &self.to, buf);
        }
        if !self.value.is_empty() {
            ::buffa::types::put_string_field(12u32, &self.value, buf);
        }
    }
    /// Compute size, then write. Primary encode entry point.
    ///
    /// # Panics
    ///
    /// Panics if the encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]) — see
    /// [`try_encode`](Self::try_encode) for the error-returning
    /// variant.
    #[inline]
    pub fn encode(&self, buf: &mut impl ::buffa::EncodeSink) {
        self.try_encode(buf).unwrap_or_else(|_| ::buffa::encode_size_overflow())
    }
    /// Encode, returning an error instead of panicking if the
    /// encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]).
    ///
    /// On `Err`, nothing is written to `buf`.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::EncodeError::MessageTooLarge`] if the
    /// encoded size exceeds the limit.
    pub fn try_encode(
        &self,
        buf: &mut impl ::buffa::EncodeSink,
    ) -> ::core::result::Result<(), ::buffa::EncodeError> {
        let mut __cache = ::buffa::SizeCache::new();
        ::buffa::checked_encode_size(self.compute_size(&mut __cache))?;
        self.write_to(&mut __cache, buf);
        ::core::result::Result::Ok(())
    }
    /// Encoded byte size of this view.
    ///
    /// # Panics
    ///
    /// Panics if the encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]) — see
    /// [`try_encoded_len`](Self::try_encoded_len) for the
    /// error-returning variant.
    #[inline]
    #[must_use]
    pub fn encoded_len(&self) -> u32 {
        self.try_encoded_len().unwrap_or_else(|_| ::buffa::encode_size_overflow())
    }
    /// Encoded byte size, returning an error instead of panicking
    /// if it exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::EncodeError::MessageTooLarge`] if the
    /// encoded size exceeds the limit.
    pub fn try_encoded_len(&self) -> ::core::result::Result<u32, ::buffa::EncodeError> {
        ::buffa::checked_encode_size(self.compute_size(&mut ::buffa::SizeCache::new()))
    }
    /// Encode this view to a new `Vec<u8>`.
    ///
    /// # Panics
    ///
    /// Panics if the encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]) — see
    /// [`try_encode_to_vec`](Self::try_encode_to_vec) for the
    /// error-returning variant. In debug builds, also panics if the
    /// two encode passes disagree on the byte count.
    #[inline]
    #[must_use]
    pub fn encode_to_vec(&self) -> ::buffa::alloc::vec::Vec<u8> {
        let mut __cache = ::buffa::SizeCache::new();
        let __size = match ::buffa::checked_encode_size(
            self.compute_size(&mut __cache),
        ) {
            ::core::result::Result::Ok(__size) => __size as usize,
            ::core::result::Result::Err(_) => ::buffa::encode_size_overflow(),
        };
        let mut __buf = ::buffa::alloc::vec::Vec::with_capacity(__size);
        self.write_to(&mut __cache, &mut __buf);
        ::buffa::debug_assert_two_pass(__buf.len(), __size);
        __buf
    }
    /// Encode to a new `Vec<u8>`, returning an error instead of
    /// panicking if the encoded size exceeds the 2 GiB protobuf
    /// limit ([`::buffa::MAX_MESSAGE_BYTES`]).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::EncodeError::MessageTooLarge`] if the
    /// encoded size exceeds the limit.
    ///
    /// # Panics
    ///
    /// In debug builds, panics if the two encode passes disagree
    /// on the byte count.
    pub fn try_encode_to_vec(
        &self,
    ) -> ::core::result::Result<::buffa::alloc::vec::Vec<u8>, ::buffa::EncodeError> {
        let mut __cache = ::buffa::SizeCache::new();
        let __size = ::buffa::checked_encode_size(self.compute_size(&mut __cache))?
            as usize;
        let mut __buf = ::buffa::alloc::vec::Vec::with_capacity(__size);
        self.write_to(&mut __cache, &mut __buf);
        ::buffa::debug_assert_two_pass(__buf.len(), __size);
        ::core::result::Result::Ok(__buf)
    }
    /// Encode this view to a new [`::buffa::bytes::Bytes`].
    ///
    /// # Panics
    ///
    /// Panics if the encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]) — see
    /// [`try_encode_to_bytes`](Self::try_encode_to_bytes) for the
    /// error-returning variant. In debug builds, also panics if the
    /// two encode passes disagree on the byte count.
    #[inline]
    #[must_use]
    pub fn encode_to_bytes(&self) -> ::buffa::bytes::Bytes {
        let mut __cache = ::buffa::SizeCache::new();
        let __size = match ::buffa::checked_encode_size(
            self.compute_size(&mut __cache),
        ) {
            ::core::result::Result::Ok(__size) => __size as usize,
            ::core::result::Result::Err(_) => ::buffa::encode_size_overflow(),
        };
        let mut __buf = ::buffa::bytes::BytesMut::with_capacity(__size);
        self.write_to(&mut __cache, &mut __buf);
        ::buffa::debug_assert_two_pass(__buf.len(), __size);
        __buf.freeze()
    }
    /// Encode to a new [`::buffa::bytes::Bytes`], returning an
    /// error instead of panicking if the encoded size exceeds the
    /// 2 GiB protobuf limit ([`::buffa::MAX_MESSAGE_BYTES`]).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::EncodeError::MessageTooLarge`] if the
    /// encoded size exceeds the limit.
    ///
    /// # Panics
    ///
    /// In debug builds, panics if the two encode passes disagree
    /// on the byte count.
    pub fn try_encode_to_bytes(
        &self,
    ) -> ::core::result::Result<::buffa::bytes::Bytes, ::buffa::EncodeError> {
        let mut __cache = ::buffa::SizeCache::new();
        let __size = ::buffa::checked_encode_size(self.compute_size(&mut __cache))?
            as usize;
        let mut __buf = ::buffa::bytes::BytesMut::with_capacity(__size);
        self.write_to(&mut __cache, &mut __buf);
        ::buffa::debug_assert_two_pass(__buf.len(), __size);
        ::core::result::Result::Ok(__buf.freeze())
    }
}
impl<'a> ::buffa::MessageName for TransferLazyView<'a> {
    const PACKAGE: &'static str = "evm.erc20.transfers.v1";
    const NAME: &'static str = "Transfer";
    const FULL_NAME: &'static str = "evm.erc20.transfers.v1.Transfer";
    const TYPE_URL: &'static str = "type.googleapis.com/evm.erc20.transfers.v1.Transfer";
}
/** Lazy view of `evm.erc20.transfers.v1.Approval`: nested and repeated message fields are
 recorded as undecoded byte ranges and decoded on access. See
 [`::buffa::LazyMessageView`] for the deferred-validation contract;
 the eager, whole-tree-validated counterpart is named `ApprovalView`.

 Oneof variants, map values, groups, and extern-typed fields (e.g.
 well-known types) hold eagerly-decoded `ApprovalView`-family
 types; only singular/repeated message fields defer.

 # Examples

 ```rust,ignore
 use buffa::LazyMessageView;

 let view = ApprovalLazyView::decode_lazy(&bytes)?;
 ```*/
#[derive(Clone, Debug, Default)]
pub struct ApprovalLazyView<'a> {
    /// -- transaction --
    ///
    /// Field 1: `tx_hash`
    pub tx_hash: &'a [u8],
    /// -- call --
    ///
    /// Field 2: `caller`
    pub caller: ::core::option::Option<&'a [u8]>,
    /// -- log --
    ///
    /// log.address
    ///
    /// Field 3: `contract`
    pub contract: &'a [u8],
    /// log.ordinal
    ///
    /// Field 4: `ordinal`
    pub ordinal: u64,
    /// log.index
    ///
    /// Field 5: `log_index`
    pub log_index: u32,
    /// -- event --
    ///
    /// Field 10: `owner`
    pub owner: &'a [u8],
    /// Field 11: `spender`
    pub spender: &'a [u8],
    /// Field 12: `value`
    pub value: &'a str,
}
impl<'a> ApprovalLazyView<'a> {
    /// Decode from `buf` under the limits carried by `ctx`, recording
    /// nested/repeated message fields as byte ranges.
    ///
    /// **Not part of the public API.**
    #[doc(hidden)]
    pub fn _decode_lazy_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let mut view = Self::default();
        view._merge_lazy(buf, ctx)?;
        ::core::result::Result::Ok(view)
    }
    /// Merge fields from `buf` into this view (proto merge semantics;
    /// deferred message fragments accumulate).
    ///
    /// **Not part of the public API.**
    #[doc(hidden)]
    pub fn _merge_lazy(
        &mut self,
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur: &'a [u8] = buf;
        while !cur.is_empty() {
            let tag = ::buffa::encoding::Tag::decode(&mut cur)?;
            match tag.field_number() {
                1u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::LengthDelimited,
                    )?;
                    view.tx_hash = ::buffa::types::borrow_bytes(&mut cur)?;
                }
                2u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::LengthDelimited,
                    )?;
                    view.caller = Some(::buffa::types::borrow_bytes(&mut cur)?);
                }
                3u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::LengthDelimited,
                    )?;
                    view.contract = ::buffa::types::borrow_bytes(&mut cur)?;
                }
                4u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::Varint,
                    )?;
                    view.ordinal = ::buffa::types::decode_uint64(&mut cur)?;
                }
                5u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::Varint,
                    )?;
                    view.log_index = ::buffa::types::decode_uint32(&mut cur)?;
                }
                10u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::LengthDelimited,
                    )?;
                    view.owner = ::buffa::types::borrow_bytes(&mut cur)?;
                }
                11u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::LengthDelimited,
                    )?;
                    view.spender = ::buffa::types::borrow_bytes(&mut cur)?;
                }
                12u32 => {
                    ::buffa::encoding::check_wire_type(
                        tag,
                        ::buffa::encoding::WireType::LengthDelimited,
                    )?;
                    view.value = ::buffa::types::borrow_str(&mut cur)?;
                }
                _ => {
                    ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
                }
            }
        }
        ::core::result::Result::Ok(())
    }
}
impl<'a> ::buffa::LazyMessageView<'a> for ApprovalLazyView<'a> {
    type Owned = super::super::Approval;
    fn decode_lazy(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        Self::_decode_lazy_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_lazy_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        Self::_decode_lazy_ctx(buf, ctx)
    }
    fn merge_lazy(
        &mut self,
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        self._merge_lazy(buf, ctx)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Approval, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        #[allow(unused_imports)]
        use ::buffa::MessageView as _;
        let __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes> = ::core::option::Option::None;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Approval {
            tx_hash: (self.tx_hash).to_vec(),
            caller: self.caller.map(|b| (b).to_vec()),
            contract: (self.contract).to_vec(),
            ordinal: self.ordinal,
            log_index: self.log_index,
            owner: (self.owner).to_vec(),
            spender: (self.spender).to_vec(),
            value: self.value.to_string(),
            ..::core::default::Default::default()
        })
    }
}
/// Re-encoding: recorded fragments are replayed byte-for-byte
/// **without validation** — wire-equivalent to the merged value, and
/// a never-accessed malformed deferred field round-trips silently.
/// Inherent rather than [`::buffa::ViewEncode`] (whose `MessageView`
/// supertrait carries the eager whole-tree-validated contract); the
/// fuller `ViewEncode` set (`encode_length_delimited`,
/// `encode_with_cache`) lives on the eager view.
impl<'a> ApprovalLazyView<'a> {
    /// Compute the encoded byte size, filling `cache` with
    /// per-message sizes consumed by a following `write_to` call.
    /// Called for that side effect by `encode`; prefer `encoded_len`
    /// when only the size is needed.
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    pub fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        #[allow(unused_imports)]
        use ::buffa::ViewEncode as _;
        let mut size = 0u64;
        if !self.tx_hash.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.tx_hash) as u64;
        }
        if let Some(ref v) = self.caller {
            size += 1u64 + ::buffa::types::bytes_encoded_len(v) as u64;
        }
        if !self.contract.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.contract) as u64;
        }
        if self.ordinal != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.ordinal) as u64;
        }
        if self.log_index != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.log_index) as u64;
        }
        if !self.owner.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.owner) as u64;
        }
        if !self.spender.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.spender) as u64;
        }
        if !self.value.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.value) as u64;
        }
        ::buffa::saturate_size(size)
    }
    /// Write the encoded bytes to `buf`, reading per-message sizes
    /// from the `cache` filled by a preceding `compute_size` call.
    /// Prefer `encode` unless threading a shared cache.
    #[allow(clippy::needless_borrow)]
    pub fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        #[allow(unused_imports)]
        use ::buffa::ViewEncode as _;
        if !self.tx_hash.is_empty() {
            ::buffa::types::put_shared_bytes_field(1u32, &self.tx_hash, buf);
        }
        if let Some(ref v) = self.caller {
            ::buffa::types::put_shared_bytes_field(2u32, v, buf);
        }
        if !self.contract.is_empty() {
            ::buffa::types::put_shared_bytes_field(3u32, &self.contract, buf);
        }
        if self.ordinal != 0u64 {
            ::buffa::types::put_uint64_field(4u32, self.ordinal, buf);
        }
        if self.log_index != 0u32 {
            ::buffa::types::put_uint32_field(5u32, self.log_index, buf);
        }
        if !self.owner.is_empty() {
            ::buffa::types::put_shared_bytes_field(10u32, &self.owner, buf);
        }
        if !self.spender.is_empty() {
            ::buffa::types::put_shared_bytes_field(11u32, &self.spender, buf);
        }
        if !self.value.is_empty() {
            ::buffa::types::put_string_field(12u32, &self.value, buf);
        }
    }
    /// Compute size, then write. Primary encode entry point.
    ///
    /// # Panics
    ///
    /// Panics if the encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]) — see
    /// [`try_encode`](Self::try_encode) for the error-returning
    /// variant.
    #[inline]
    pub fn encode(&self, buf: &mut impl ::buffa::EncodeSink) {
        self.try_encode(buf).unwrap_or_else(|_| ::buffa::encode_size_overflow())
    }
    /// Encode, returning an error instead of panicking if the
    /// encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]).
    ///
    /// On `Err`, nothing is written to `buf`.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::EncodeError::MessageTooLarge`] if the
    /// encoded size exceeds the limit.
    pub fn try_encode(
        &self,
        buf: &mut impl ::buffa::EncodeSink,
    ) -> ::core::result::Result<(), ::buffa::EncodeError> {
        let mut __cache = ::buffa::SizeCache::new();
        ::buffa::checked_encode_size(self.compute_size(&mut __cache))?;
        self.write_to(&mut __cache, buf);
        ::core::result::Result::Ok(())
    }
    /// Encoded byte size of this view.
    ///
    /// # Panics
    ///
    /// Panics if the encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]) — see
    /// [`try_encoded_len`](Self::try_encoded_len) for the
    /// error-returning variant.
    #[inline]
    #[must_use]
    pub fn encoded_len(&self) -> u32 {
        self.try_encoded_len().unwrap_or_else(|_| ::buffa::encode_size_overflow())
    }
    /// Encoded byte size, returning an error instead of panicking
    /// if it exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::EncodeError::MessageTooLarge`] if the
    /// encoded size exceeds the limit.
    pub fn try_encoded_len(&self) -> ::core::result::Result<u32, ::buffa::EncodeError> {
        ::buffa::checked_encode_size(self.compute_size(&mut ::buffa::SizeCache::new()))
    }
    /// Encode this view to a new `Vec<u8>`.
    ///
    /// # Panics
    ///
    /// Panics if the encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]) — see
    /// [`try_encode_to_vec`](Self::try_encode_to_vec) for the
    /// error-returning variant. In debug builds, also panics if the
    /// two encode passes disagree on the byte count.
    #[inline]
    #[must_use]
    pub fn encode_to_vec(&self) -> ::buffa::alloc::vec::Vec<u8> {
        let mut __cache = ::buffa::SizeCache::new();
        let __size = match ::buffa::checked_encode_size(
            self.compute_size(&mut __cache),
        ) {
            ::core::result::Result::Ok(__size) => __size as usize,
            ::core::result::Result::Err(_) => ::buffa::encode_size_overflow(),
        };
        let mut __buf = ::buffa::alloc::vec::Vec::with_capacity(__size);
        self.write_to(&mut __cache, &mut __buf);
        ::buffa::debug_assert_two_pass(__buf.len(), __size);
        __buf
    }
    /// Encode to a new `Vec<u8>`, returning an error instead of
    /// panicking if the encoded size exceeds the 2 GiB protobuf
    /// limit ([`::buffa::MAX_MESSAGE_BYTES`]).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::EncodeError::MessageTooLarge`] if the
    /// encoded size exceeds the limit.
    ///
    /// # Panics
    ///
    /// In debug builds, panics if the two encode passes disagree
    /// on the byte count.
    pub fn try_encode_to_vec(
        &self,
    ) -> ::core::result::Result<::buffa::alloc::vec::Vec<u8>, ::buffa::EncodeError> {
        let mut __cache = ::buffa::SizeCache::new();
        let __size = ::buffa::checked_encode_size(self.compute_size(&mut __cache))?
            as usize;
        let mut __buf = ::buffa::alloc::vec::Vec::with_capacity(__size);
        self.write_to(&mut __cache, &mut __buf);
        ::buffa::debug_assert_two_pass(__buf.len(), __size);
        ::core::result::Result::Ok(__buf)
    }
    /// Encode this view to a new [`::buffa::bytes::Bytes`].
    ///
    /// # Panics
    ///
    /// Panics if the encoded size exceeds the 2 GiB protobuf limit
    /// ([`::buffa::MAX_MESSAGE_BYTES`]) — see
    /// [`try_encode_to_bytes`](Self::try_encode_to_bytes) for the
    /// error-returning variant. In debug builds, also panics if the
    /// two encode passes disagree on the byte count.
    #[inline]
    #[must_use]
    pub fn encode_to_bytes(&self) -> ::buffa::bytes::Bytes {
        let mut __cache = ::buffa::SizeCache::new();
        let __size = match ::buffa::checked_encode_size(
            self.compute_size(&mut __cache),
        ) {
            ::core::result::Result::Ok(__size) => __size as usize,
            ::core::result::Result::Err(_) => ::buffa::encode_size_overflow(),
        };
        let mut __buf = ::buffa::bytes::BytesMut::with_capacity(__size);
        self.write_to(&mut __cache, &mut __buf);
        ::buffa::debug_assert_two_pass(__buf.len(), __size);
        __buf.freeze()
    }
    /// Encode to a new [`::buffa::bytes::Bytes`], returning an
    /// error instead of panicking if the encoded size exceeds the
    /// 2 GiB protobuf limit ([`::buffa::MAX_MESSAGE_BYTES`]).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::EncodeError::MessageTooLarge`] if the
    /// encoded size exceeds the limit.
    ///
    /// # Panics
    ///
    /// In debug builds, panics if the two encode passes disagree
    /// on the byte count.
    pub fn try_encode_to_bytes(
        &self,
    ) -> ::core::result::Result<::buffa::bytes::Bytes, ::buffa::EncodeError> {
        let mut __cache = ::buffa::SizeCache::new();
        let __size = ::buffa::checked_encode_size(self.compute_size(&mut __cache))?
            as usize;
        let mut __buf = ::buffa::bytes::BytesMut::with_capacity(__size);
        self.write_to(&mut __cache, &mut __buf);
        ::buffa::debug_assert_two_pass(__buf.len(), __size);
        ::core::result::Result::Ok(__buf.freeze())
    }
}
impl<'a> ::buffa::MessageName for ApprovalLazyView<'a> {
    const PACKAGE: &'static str = "evm.erc20.transfers.v1";
    const NAME: &'static str = "Approval";
    const FULL_NAME: &'static str = "evm.erc20.transfers.v1.Approval";
    const TYPE_URL: &'static str = "type.googleapis.com/evm.erc20.transfers.v1.Approval";
}
