// @generated by buffa-codegen. DO NOT EDIT.
// source: core/market_contract.proto

#[derive(Clone, PartialEq, Default)]
pub struct MarketSellAssetContract {
    /// Field 1: `owner_address`
    pub owner_address: ::buffa::alloc::vec::Vec<u8>,
    /// Field 2: `sell_token_id`
    pub sell_token_id: ::buffa::alloc::vec::Vec<u8>,
    /// Field 3: `sell_token_quantity`
    pub sell_token_quantity: i64,
    /// Field 4: `buy_token_id`
    pub buy_token_id: ::buffa::alloc::vec::Vec<u8>,
    /// Field 5: `buy_token_quantity`
    pub buy_token_quantity: i64,
}
impl ::core::fmt::Debug for MarketSellAssetContract {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("MarketSellAssetContract")
            .field("owner_address", &self.owner_address)
            .field("sell_token_id", &self.sell_token_id)
            .field("sell_token_quantity", &self.sell_token_quantity)
            .field("buy_token_id", &self.buy_token_id)
            .field("buy_token_quantity", &self.buy_token_quantity)
            .finish()
    }
}
impl MarketSellAssetContract {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/protocol.MarketSellAssetContract";
}
::buffa::impl_default_instance!(MarketSellAssetContract);
impl ::buffa::MessageName for MarketSellAssetContract {
    const PACKAGE: &'static str = "protocol";
    const NAME: &'static str = "MarketSellAssetContract";
    const FULL_NAME: &'static str = "protocol.MarketSellAssetContract";
    const TYPE_URL: &'static str = "type.googleapis.com/protocol.MarketSellAssetContract";
}
impl ::buffa::Message for MarketSellAssetContract {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.owner_address.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.owner_address) as u64;
        }
        if !self.sell_token_id.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.sell_token_id) as u64;
        }
        if self.sell_token_quantity != 0i64 {
            size
                += 1u64
                    + ::buffa::types::int64_encoded_len(self.sell_token_quantity) as u64;
        }
        if !self.buy_token_id.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.buy_token_id) as u64;
        }
        if self.buy_token_quantity != 0i64 {
            size
                += 1u64
                    + ::buffa::types::int64_encoded_len(self.buy_token_quantity) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.owner_address.is_empty() {
            ::buffa::types::put_shared_bytes_field(1u32, &self.owner_address, buf);
        }
        if !self.sell_token_id.is_empty() {
            ::buffa::types::put_shared_bytes_field(2u32, &self.sell_token_id, buf);
        }
        if self.sell_token_quantity != 0i64 {
            ::buffa::types::put_int64_field(3u32, self.sell_token_quantity, buf);
        }
        if !self.buy_token_id.is_empty() {
            ::buffa::types::put_shared_bytes_field(4u32, &self.buy_token_id, buf);
        }
        if self.buy_token_quantity != 0i64 {
            ::buffa::types::put_int64_field(5u32, self.buy_token_quantity, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.owner_address, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.sell_token_id, buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.sell_token_quantity = ::buffa::types::decode_int64(buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.buy_token_id, buf)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.buy_token_quantity = ::buffa::types::decode_int64(buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.owner_address.clear();
        self.sell_token_id.clear();
        self.sell_token_quantity = 0i64;
        self.buy_token_id.clear();
        self.buy_token_quantity = 0i64;
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct MarketCancelOrderContract {
    /// Field 1: `owner_address`
    pub owner_address: ::buffa::alloc::vec::Vec<u8>,
    /// Field 2: `order_id`
    pub order_id: ::buffa::alloc::vec::Vec<u8>,
}
impl ::core::fmt::Debug for MarketCancelOrderContract {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("MarketCancelOrderContract")
            .field("owner_address", &self.owner_address)
            .field("order_id", &self.order_id)
            .finish()
    }
}
impl MarketCancelOrderContract {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/protocol.MarketCancelOrderContract";
}
::buffa::impl_default_instance!(MarketCancelOrderContract);
impl ::buffa::MessageName for MarketCancelOrderContract {
    const PACKAGE: &'static str = "protocol";
    const NAME: &'static str = "MarketCancelOrderContract";
    const FULL_NAME: &'static str = "protocol.MarketCancelOrderContract";
    const TYPE_URL: &'static str = "type.googleapis.com/protocol.MarketCancelOrderContract";
}
impl ::buffa::Message for MarketCancelOrderContract {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.owner_address.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.owner_address) as u64;
        }
        if !self.order_id.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.order_id) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.owner_address.is_empty() {
            ::buffa::types::put_shared_bytes_field(1u32, &self.owner_address, buf);
        }
        if !self.order_id.is_empty() {
            ::buffa::types::put_shared_bytes_field(2u32, &self.order_id, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.owner_address, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.order_id, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.owner_address.clear();
        self.order_id.clear();
    }
}
