// @generated by buffa-codegen. DO NOT EDIT.
// source: core/Discover.proto

#[derive(Clone, PartialEq, Default)]
#[allow(non_snake_case)]
pub struct Endpoint {
    /// Field 1: `address`
    pub address: ::buffa::alloc::vec::Vec<u8>,
    /// Field 2: `port`
    pub port: i32,
    /// Field 3: `nodeId`
    pub nodeId: ::buffa::alloc::vec::Vec<u8>,
}
impl ::core::fmt::Debug for Endpoint {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Endpoint")
            .field("address", &self.address)
            .field("port", &self.port)
            .field("nodeId", &self.nodeId)
            .finish()
    }
}
impl Endpoint {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/protocol.Endpoint";
}
::buffa::impl_default_instance!(Endpoint);
impl ::buffa::MessageName for Endpoint {
    const PACKAGE: &'static str = "protocol";
    const NAME: &'static str = "Endpoint";
    const FULL_NAME: &'static str = "protocol.Endpoint";
    const TYPE_URL: &'static str = "type.googleapis.com/protocol.Endpoint";
}
impl ::buffa::Message for Endpoint {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.address.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.address) as u64;
        }
        if self.port != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.port) as u64;
        }
        if !self.nodeId.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.nodeId) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.address.is_empty() {
            ::buffa::types::put_shared_bytes_field(1u32, &self.address, buf);
        }
        if self.port != 0i32 {
            ::buffa::types::put_int32_field(2u32, self.port, buf);
        }
        if !self.nodeId.is_empty() {
            ::buffa::types::put_shared_bytes_field(3u32, &self.nodeId, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.address, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.port = ::buffa::types::decode_int32(buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.nodeId, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.address.clear();
        self.port = 0i32;
        self.nodeId.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct PingMessage {
    /// Field 1: `from`
    pub from: ::buffa::MessageField<Endpoint, ::buffa::Inline<Endpoint>>,
    /// Field 2: `to`
    pub to: ::buffa::MessageField<Endpoint, ::buffa::Inline<Endpoint>>,
    /// Field 3: `version`
    pub version: i32,
    /// Field 4: `timestamp`
    pub timestamp: i64,
}
impl ::core::fmt::Debug for PingMessage {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("PingMessage")
            .field("from", &self.from)
            .field("to", &self.to)
            .field("version", &self.version)
            .field("timestamp", &self.timestamp)
            .finish()
    }
}
impl PingMessage {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/protocol.PingMessage";
}
::buffa::impl_default_instance!(PingMessage);
impl ::buffa::MessageName for PingMessage {
    const PACKAGE: &'static str = "protocol";
    const NAME: &'static str = "PingMessage";
    const FULL_NAME: &'static str = "protocol.PingMessage";
    const TYPE_URL: &'static str = "type.googleapis.com/protocol.PingMessage";
}
impl ::buffa::Message for PingMessage {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.from.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.from.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if self.to.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.to.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if self.version != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.version) as u64;
        }
        if self.timestamp != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.timestamp) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.from.is_set() {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.from.write_to(__cache, buf);
        }
        if self.to.is_set() {
            ::buffa::types::put_len_delimited_header(
                2u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.to.write_to(__cache, buf);
        }
        if self.version != 0i32 {
            ::buffa::types::put_int32_field(3u32, self.version, buf);
        }
        if self.timestamp != 0i64 {
            ::buffa::types::put_int64_field(4u32, self.timestamp, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.from.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.to.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.version = ::buffa::types::decode_int32(buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.timestamp = ::buffa::types::decode_int64(buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.from = ::buffa::MessageField::none();
        self.to = ::buffa::MessageField::none();
        self.version = 0i32;
        self.timestamp = 0i64;
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct PongMessage {
    /// Field 1: `from`
    pub from: ::buffa::MessageField<Endpoint, ::buffa::Inline<Endpoint>>,
    /// Field 2: `echo`
    pub echo: i32,
    /// Field 3: `timestamp`
    pub timestamp: i64,
}
impl ::core::fmt::Debug for PongMessage {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("PongMessage")
            .field("from", &self.from)
            .field("echo", &self.echo)
            .field("timestamp", &self.timestamp)
            .finish()
    }
}
impl PongMessage {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/protocol.PongMessage";
}
::buffa::impl_default_instance!(PongMessage);
impl ::buffa::MessageName for PongMessage {
    const PACKAGE: &'static str = "protocol";
    const NAME: &'static str = "PongMessage";
    const FULL_NAME: &'static str = "protocol.PongMessage";
    const TYPE_URL: &'static str = "type.googleapis.com/protocol.PongMessage";
}
impl ::buffa::Message for PongMessage {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.from.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.from.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if self.echo != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.echo) as u64;
        }
        if self.timestamp != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.timestamp) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.from.is_set() {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.from.write_to(__cache, buf);
        }
        if self.echo != 0i32 {
            ::buffa::types::put_int32_field(2u32, self.echo, buf);
        }
        if self.timestamp != 0i64 {
            ::buffa::types::put_int64_field(3u32, self.timestamp, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.from.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.echo = ::buffa::types::decode_int32(buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.timestamp = ::buffa::types::decode_int64(buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.from = ::buffa::MessageField::none();
        self.echo = 0i32;
        self.timestamp = 0i64;
    }
}
#[derive(Clone, PartialEq, Default)]
#[allow(non_snake_case)]
pub struct FindNeighbours {
    /// Field 1: `from`
    pub from: ::buffa::MessageField<Endpoint, ::buffa::Inline<Endpoint>>,
    /// Field 2: `targetId`
    pub targetId: ::buffa::alloc::vec::Vec<u8>,
    /// Field 3: `timestamp`
    pub timestamp: i64,
}
impl ::core::fmt::Debug for FindNeighbours {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("FindNeighbours")
            .field("from", &self.from)
            .field("targetId", &self.targetId)
            .field("timestamp", &self.timestamp)
            .finish()
    }
}
impl FindNeighbours {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/protocol.FindNeighbours";
}
::buffa::impl_default_instance!(FindNeighbours);
impl ::buffa::MessageName for FindNeighbours {
    const PACKAGE: &'static str = "protocol";
    const NAME: &'static str = "FindNeighbours";
    const FULL_NAME: &'static str = "protocol.FindNeighbours";
    const TYPE_URL: &'static str = "type.googleapis.com/protocol.FindNeighbours";
}
impl ::buffa::Message for FindNeighbours {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.from.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.from.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if !self.targetId.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.targetId) as u64;
        }
        if self.timestamp != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.timestamp) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.from.is_set() {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.from.write_to(__cache, buf);
        }
        if !self.targetId.is_empty() {
            ::buffa::types::put_shared_bytes_field(2u32, &self.targetId, buf);
        }
        if self.timestamp != 0i64 {
            ::buffa::types::put_int64_field(3u32, self.timestamp, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.from.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.targetId, buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.timestamp = ::buffa::types::decode_int64(buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.from = ::buffa::MessageField::none();
        self.targetId.clear();
        self.timestamp = 0i64;
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct Neighbours {
    /// Field 1: `from`
    pub from: ::buffa::MessageField<Endpoint, ::buffa::Inline<Endpoint>>,
    /// Field 2: `neighbours`
    pub neighbours: ::buffa::alloc::vec::Vec<Endpoint>,
    /// Field 3: `timestamp`
    pub timestamp: i64,
}
impl ::core::fmt::Debug for Neighbours {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Neighbours")
            .field("from", &self.from)
            .field("neighbours", &self.neighbours)
            .field("timestamp", &self.timestamp)
            .finish()
    }
}
impl Neighbours {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/protocol.Neighbours";
}
::buffa::impl_default_instance!(Neighbours);
impl ::buffa::MessageName for Neighbours {
    const PACKAGE: &'static str = "protocol";
    const NAME: &'static str = "Neighbours";
    const FULL_NAME: &'static str = "protocol.Neighbours";
    const TYPE_URL: &'static str = "type.googleapis.com/protocol.Neighbours";
}
impl ::buffa::Message for Neighbours {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.from.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.from.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        for v in &self.neighbours {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if self.timestamp != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.timestamp) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.from.is_set() {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.from.write_to(__cache, buf);
        }
        for v in &self.neighbours {
            ::buffa::types::put_len_delimited_header(
                2u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
        if self.timestamp != 0i64 {
            ::buffa::types::put_int64_field(3u32, self.timestamp, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.from.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&elem),
                )?;
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.neighbours.push(elem);
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.timestamp = ::buffa::types::decode_int64(buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.from = ::buffa::MessageField::none();
        self.neighbours.clear();
        self.timestamp = 0i64;
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct BackupMessage {
    /// Field 1: `flag`
    pub flag: bool,
    /// Field 2: `priority`
    pub priority: i32,
}
impl ::core::fmt::Debug for BackupMessage {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("BackupMessage")
            .field("flag", &self.flag)
            .field("priority", &self.priority)
            .finish()
    }
}
impl BackupMessage {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/protocol.BackupMessage";
}
::buffa::impl_default_instance!(BackupMessage);
impl ::buffa::MessageName for BackupMessage {
    const PACKAGE: &'static str = "protocol";
    const NAME: &'static str = "BackupMessage";
    const FULL_NAME: &'static str = "protocol.BackupMessage";
    const TYPE_URL: &'static str = "type.googleapis.com/protocol.BackupMessage";
}
impl ::buffa::Message for BackupMessage {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.flag {
            size += 1u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        if self.priority != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.priority) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.flag {
            ::buffa::types::put_bool_field(1u32, self.flag, buf);
        }
        if self.priority != 0i32 {
            ::buffa::types::put_int32_field(2u32, self.priority, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.flag = ::buffa::types::decode_bool(buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.priority = ::buffa::types::decode_int32(buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.flag = false;
        self.priority = 0i32;
    }
}
