//! Protobuf types for the Tron foundational modules.
//!
//! Generated by the `buf.build/anthropics/buffa` plugin; run `substreams protogen` to regenerate.

macro_rules! include_buffa {
    ($package:literal) => {
        include!(concat!($package, ".mod.rs"));
    };
}

pub mod protocol {
    include_buffa!("protocol");
}

pub mod sf {
    pub mod substreams {
        pub mod tron {
            pub mod v1 {
                include_buffa!("sf.substreams.tron.v1");
            }
        }

        pub mod v1 {
            include_buffa!("sf.substreams.v1");
        }
    }

    pub mod tron {
        pub mod r#type {
            pub mod v1 {
                include_buffa!("sf.tron.type.v1");
            }
        }
    }
}
