// @generated by buffa-codegen. DO NOT EDIT.

include!("sf.tron.type.v1.block.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.tron.type.v1.block.__view.rs");
    }
    pub mod lazy_view {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.tron.type.v1.block.__lazy_view.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::BlockView;
#[doc(inline)]
pub use self::__buffa::view::BlockOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::BlockLazyView;
#[doc(inline)]
pub use self::__buffa::view::BlockHeaderView;
#[doc(inline)]
pub use self::__buffa::view::BlockHeaderOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::BlockHeaderLazyView;
#[doc(inline)]
pub use self::__buffa::view::TransactionView;
#[doc(inline)]
pub use self::__buffa::view::TransactionOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::TransactionLazyView;
