[package]
name = "stellar-common"
version = "0.6.1"
description = "Substreams showcasing the building blocks of Stellar"
edition = "2021"
repository = "https://github.com/streamingfast/substreams-foundational-modules/tree/develop/stellar-common#stellar-foundational-modules"
license = "Apache 2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
bigdecimal = "0.4.7"
bs58 = { workspace = true }
num-bigint = { workspace = true }
buffa = { workspace = true }
buffa-types = { workspace = true }
substreams = { workspace = true }
anyhow = { workspace = true }
base64 = { workspace = true }
stellar-xdr = { version = "27.0", default-features = true, features = [
    "serde",
    "alloc",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[target.wasm32-unknown-unknown.dependencies]
getrandom = { version = "0.2", features = ["custom"] }

[dev-dependencies]
pretty_assertions = "1.4"
